"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.mcp.mcp_access_management import register_access_management_tools
from onetrust_api.mcp.mcp_ai_governance import register_ai_governance_tools
from onetrust_api.mcp.mcp_assessments import register_assessments_tools
from onetrust_api.mcp.mcp_audit_management import register_audit_management_tools
from onetrust_api.mcp.mcp_bulk_export import register_bulk_export_tools
from onetrust_api.mcp.mcp_cmp import register_cmp_tools
from onetrust_api.mcp.mcp_compliance_automation import register_compliance_automation_tools
from onetrust_api.mcp.mcp_consent_interfaces import register_consent_interfaces_tools
from onetrust_api.mcp.mcp_consent_receipts import register_consent_receipts_tools
from onetrust_api.mcp.mcp_cookie_consent import register_cookie_consent_tools
from onetrust_api.mcp.mcp_cookie_consent_legacy import register_cookie_consent_legacy_tools
from onetrust_api.mcp.mcp_cookie_domain_data import register_cookie_domain_data_tools
from onetrust_api.mcp.mcp_cross_device_consent import register_cross_device_consent_tools
from onetrust_api.mcp.mcp_data_catalog import register_data_catalog_tools
from onetrust_api.mcp.mcp_data_discovery import register_data_discovery_tools
from onetrust_api.mcp.mcp_data_discovery_worker import register_data_discovery_worker_tools
from onetrust_api.mcp.mcp_data_mapping import register_data_mapping_tools
from onetrust_api.mcp.mcp_data_mapping_legacy import register_data_mapping_legacy_tools
from onetrust_api.mcp.mcp_documents import register_documents_tools
from onetrust_api.mcp.mcp_dsar import register_dsar_tools
from onetrust_api.mcp.mcp_esg import register_esg_tools
from onetrust_api.mcp.mcp_incidents import register_incidents_tools
from onetrust_api.mcp.mcp_integrations import register_integrations_tools
from onetrust_api.mcp.mcp_inventory import register_inventory_tools
from onetrust_api.mcp.mcp_issues_management import register_issues_management_tools
from onetrust_api.mcp.mcp_it_risk_management import register_it_risk_management_tools
from onetrust_api.mcp.mcp_mobile_app_consent import register_mobile_app_consent_tools
from onetrust_api.mcp.mcp_object_manager import register_object_manager_tools
from onetrust_api.mcp.mcp_policy_management import register_policy_management_tools
from onetrust_api.mcp.mcp_privacy_notices import register_privacy_notices_tools
from onetrust_api.mcp.mcp_task_management import register_task_management_tools
from onetrust_api.mcp.mcp_tprm import register_tprm_tools
from onetrust_api.mcp.mcp_training import register_training_tools
from onetrust_api.mcp.mcp_universal_consent import register_universal_consent_tools
from onetrust_api.mcp.mcp_user_provisioning import register_user_provisioning_tools
from onetrust_api.mcp.mcp_custom_api import register_custom_api_tools

# (tag, toggle_env_var, register_fn) — consumed by mcp_server.get_mcp_instance().
TOOL_REGISTRY = [
    ("access_management", "ACCESS_MANAGEMENTTOOL", register_access_management_tools),
    ("ai_governance", "AI_GOVERNANCETOOL", register_ai_governance_tools),
    ("assessments", "ASSESSMENTSTOOL", register_assessments_tools),
    ("audit_management", "AUDIT_MANAGEMENTTOOL", register_audit_management_tools),
    ("bulk_export", "BULK_EXPORTTOOL", register_bulk_export_tools),
    ("cmp", "CMPTOOL", register_cmp_tools),
    ("compliance_automation", "COMPLIANCE_AUTOMATIONTOOL", register_compliance_automation_tools),
    ("consent_interfaces", "CONSENT_INTERFACESTOOL", register_consent_interfaces_tools),
    ("consent_receipts", "CONSENT_RECEIPTSTOOL", register_consent_receipts_tools),
    ("cookie_consent", "COOKIE_CONSENTTOOL", register_cookie_consent_tools),
    ("cookie_consent_legacy", "COOKIE_CONSENT_LEGACYTOOL", register_cookie_consent_legacy_tools),
    ("cookie_domain_data", "COOKIE_DOMAIN_DATATOOL", register_cookie_domain_data_tools),
    ("cross_device_consent", "CROSS_DEVICE_CONSENTTOOL", register_cross_device_consent_tools),
    ("data_catalog", "DATA_CATALOGTOOL", register_data_catalog_tools),
    ("data_discovery", "DATA_DISCOVERYTOOL", register_data_discovery_tools),
    ("data_discovery_worker", "DATA_DISCOVERY_WORKERTOOL", register_data_discovery_worker_tools),
    ("data_mapping", "DATA_MAPPINGTOOL", register_data_mapping_tools),
    ("data_mapping_legacy", "DATA_MAPPING_LEGACYTOOL", register_data_mapping_legacy_tools),
    ("documents", "DOCUMENTSTOOL", register_documents_tools),
    ("dsar", "DSARTOOL", register_dsar_tools),
    ("esg", "ESGTOOL", register_esg_tools),
    ("incidents", "INCIDENTSTOOL", register_incidents_tools),
    ("integrations", "INTEGRATIONSTOOL", register_integrations_tools),
    ("inventory", "INVENTORYTOOL", register_inventory_tools),
    ("issues_management", "ISSUES_MANAGEMENTTOOL", register_issues_management_tools),
    ("it_risk_management", "IT_RISK_MANAGEMENTTOOL", register_it_risk_management_tools),
    ("mobile_app_consent", "MOBILE_APP_CONSENTTOOL", register_mobile_app_consent_tools),
    ("object_manager", "OBJECT_MANAGERTOOL", register_object_manager_tools),
    ("policy_management", "POLICY_MANAGEMENTTOOL", register_policy_management_tools),
    ("privacy_notices", "PRIVACY_NOTICESTOOL", register_privacy_notices_tools),
    ("task_management", "TASK_MANAGEMENTTOOL", register_task_management_tools),
    ("tprm", "TPRMTOOL", register_tprm_tools),
    ("training", "TRAININGTOOL", register_training_tools),
    ("universal_consent", "UNIVERSAL_CONSENTTOOL", register_universal_consent_tools),
    ("user_provisioning", "USER_PROVISIONINGTOOL", register_user_provisioning_tools),
    ("custom_api", "CUSTOM_APITOOL", register_custom_api_tools),
]

__all__ = [
    "register_access_management_tools",
    "register_ai_governance_tools",
    "register_assessments_tools",
    "register_audit_management_tools",
    "register_bulk_export_tools",
    "register_cmp_tools",
    "register_compliance_automation_tools",
    "register_consent_interfaces_tools",
    "register_consent_receipts_tools",
    "register_cookie_consent_tools",
    "register_cookie_consent_legacy_tools",
    "register_cookie_domain_data_tools",
    "register_cross_device_consent_tools",
    "register_data_catalog_tools",
    "register_data_discovery_tools",
    "register_data_discovery_worker_tools",
    "register_data_mapping_tools",
    "register_data_mapping_legacy_tools",
    "register_documents_tools",
    "register_dsar_tools",
    "register_esg_tools",
    "register_incidents_tools",
    "register_integrations_tools",
    "register_inventory_tools",
    "register_issues_management_tools",
    "register_it_risk_management_tools",
    "register_mobile_app_consent_tools",
    "register_object_manager_tools",
    "register_policy_management_tools",
    "register_privacy_notices_tools",
    "register_task_management_tools",
    "register_tprm_tools",
    "register_training_tools",
    "register_universal_consent_tools",
    "register_user_provisioning_tools",
    "register_custom_api_tools",
    "TOOL_REGISTRY",
]

