"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client

_UNHANDLED = object()


def _dispatch_mobile_app_consent_1(action, kwargs, client):
    # applicationdata .. applicationdata (1 actions)
    if action == "applicationdata":
        return client.applicationdata(**kwargs)
    return _UNHANDLED


_MOBILE_APP_CONSENT_DISPATCHERS = (_dispatch_mobile_app_consent_1,)


def register_mobile_app_consent_tools(mcp: FastMCP):
    @mcp.tool(tags={"mobile_app_consent"})
    async def onetrust_mobile_app_consent(
        action: str = Field(description="Action to perform. One of: 'applicationdata'"),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust mobile app consent operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_mobile_app_consent action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {type(e).__name__}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        for _dispatch in _MOBILE_APP_CONSENT_DISPATCHERS:
            _result = _dispatch(action, kwargs, client)
            if _result is not _UNHANDLED:
                return _result
        raise ValueError(f"Unknown action: {action}")
