"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client

_UNHANDLED = object()


def _dispatch_issues_management_1(action, kwargs, client):
    # get_attributes_by_schema_name_using_get .. get_issue_related_tasks_using_get (9 actions)
    if action == "get_attributes_by_schema_name_using_get":
        return client.get_attributes_by_schema_name_using_get(**kwargs)
    elif action == "create_issue_relationship_links_using_post":
        return client.create_issue_relationship_links_using_post(**kwargs)
    elif action == "get_issue_links_using_get":
        return client.get_issue_links_using_get(**kwargs)
    elif action == "create_issue_using_post":
        return client.create_issue_using_post(**kwargs)
    elif action == "find_all_issues_by_filter_using_post":
        return client.find_all_issues_by_filter_using_post(**kwargs)
    elif action == "get_issue_using_get":
        return client.get_issue_using_get(**kwargs)
    elif action == "update_issue_using_put":
        return client.update_issue_using_put(**kwargs)
    elif action == "update_issue_using_patch":
        return client.update_issue_using_patch(**kwargs)
    elif action == "get_issue_related_tasks_using_get":
        return client.get_issue_related_tasks_using_get(**kwargs)
    return _UNHANDLED


_ISSUES_MANAGEMENT_DISPATCHERS = (_dispatch_issues_management_1,)


def register_issues_management_tools(mcp: FastMCP):
    @mcp.tool(tags={"issues_management"})
    async def onetrust_issues_management(
        action: str = Field(
            description="Action to perform. One of: 'get_attributes_by_schema_name_using_get', 'create_issue_relationship_links_using_post', 'get_issue_links_using_get', 'create_issue_using_post', 'find_all_issues_by_filter_using_post', 'get_issue_using_get', 'update_issue_using_put', 'update_issue_using_patch', 'get_issue_related_tasks_using_get'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust issues management operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_issues_management action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {type(e).__name__}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        for _dispatch in _ISSUES_MANAGEMENT_DISPATCHERS:
            _result = _dispatch(action, kwargs, client)
            if _result is not _UNHANDLED:
                return _result
        raise ValueError(f"Unknown action: {action}")
