"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client

_UNHANDLED = object()


def _dispatch_consent_interfaces_1(action, kwargs, client):
    # get_realtime_preferences .. get_realtime_preferences (1 actions)
    if action == "get_realtime_preferences":
        return client.get_realtime_preferences(**kwargs)
    return _UNHANDLED


_CONSENT_INTERFACES_DISPATCHERS = (_dispatch_consent_interfaces_1,)


def register_consent_interfaces_tools(mcp: FastMCP):
    @mcp.tool(tags={"consent_interfaces"})
    async def onetrust_consent_interfaces(
        action: str = Field(
            description="Action to perform. One of: 'get_realtime_preferences'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust consent interfaces operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_consent_interfaces action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {type(e).__name__}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        for _dispatch in _CONSENT_INTERFACES_DISPATCHERS:
            _result = _dispatch(action, kwargs, client)
            if _result is not _UNHANDLED:
                return _result
        raise ValueError(f"Unknown action: {action}")
