"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_cookie_consent_tools(mcp: FastMCP):
    @mcp.tool(tags={"cookie_consent"})
    async def onetrust_cookie_consent(
        action: str = Field(
            description="Action to perform. One of: 'create_application', 'scan_application', 'get_applications', 'get_application_branding_attribute_list', 'update_application_branding_attributes_for_public_api', 'publish_app_script', 'get_app_script_details', 'get_categorized_cookies', 'publish_script_to_site', 'get_script_for_website', 'delete_domain', 'create_domain_group', 'get_script_details', 'download_script_file', 'get_branding_attribute_list', 'update_branding_attributes_for_public_api', 'get_geo_rule_groups', 'get_geo_rule_group_details', 'assign_entities_to_geo_rule_group', 'get_templates', 'get_template_details', 'get_domains_scanned_by_sort', 'add_scans', 'archive_scans', 'bulk_edit_cookies', 'bulk_add_cookies', 'bulk_delete_cookies', 'schedule_scans', 'bulk_cancel_domain_schedule', 'get_domain_scans', 'get_scan_delta_details', 'get_detailed_scan_result_information', 'get_scan_result_summary', 'get_cookies_by_filter', 'check_scans_status', 'cancel_scan', 'recategorize_cookies_by_scan'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust cookie consent operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_cookie_consent action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "create_application":
            return client.create_application(**kwargs)
        elif action == "scan_application":
            return client.scan_application(**kwargs)
        elif action == "get_applications":
            return client.get_applications(**kwargs)
        elif action == "get_application_branding_attribute_list":
            return client.get_application_branding_attribute_list(**kwargs)
        elif action == "update_application_branding_attributes_for_public_api":
            return client.update_application_branding_attributes_for_public_api(
                **kwargs
            )
        elif action == "publish_app_script":
            return client.publish_app_script(**kwargs)
        elif action == "get_app_script_details":
            return client.get_app_script_details(**kwargs)
        elif action == "get_categorized_cookies":
            return client.get_categorized_cookies(**kwargs)
        elif action == "publish_script_to_site":
            return client.publish_script_to_site(**kwargs)
        elif action == "get_script_for_website":
            return client.get_script_for_website(**kwargs)
        elif action == "delete_domain":
            return client.delete_domain(**kwargs)
        elif action == "create_domain_group":
            return client.create_domain_group(**kwargs)
        elif action == "get_script_details":
            return client.get_script_details(**kwargs)
        elif action == "download_script_file":
            return client.download_script_file(**kwargs)
        elif action == "get_branding_attribute_list":
            return client.get_branding_attribute_list(**kwargs)
        elif action == "update_branding_attributes_for_public_api":
            return client.update_branding_attributes_for_public_api(**kwargs)
        elif action == "get_geo_rule_groups":
            return client.get_geo_rule_groups(**kwargs)
        elif action == "get_geo_rule_group_details":
            return client.get_geo_rule_group_details(**kwargs)
        elif action == "assign_entities_to_geo_rule_group":
            return client.assign_entities_to_geo_rule_group(**kwargs)
        elif action == "get_templates":
            return client.get_templates(**kwargs)
        elif action == "get_template_details":
            return client.get_template_details(**kwargs)
        elif action == "get_domains_scanned_by_sort":
            return client.get_domains_scanned_by_sort(**kwargs)
        elif action == "add_scans":
            return client.add_scans(**kwargs)
        elif action == "archive_scans":
            return client.archive_scans(**kwargs)
        elif action == "bulk_edit_cookies":
            return client.bulk_edit_cookies(**kwargs)
        elif action == "bulk_add_cookies":
            return client.bulk_add_cookies(**kwargs)
        elif action == "bulk_delete_cookies":
            return client.bulk_delete_cookies(**kwargs)
        elif action == "schedule_scans":
            return client.schedule_scans(**kwargs)
        elif action == "bulk_cancel_domain_schedule":
            return client.bulk_cancel_domain_schedule(**kwargs)
        elif action == "get_domain_scans":
            return client.get_domain_scans(**kwargs)
        elif action == "get_scan_delta_details":
            return client.get_scan_delta_details(**kwargs)
        elif action == "get_detailed_scan_result_information":
            return client.get_detailed_scan_result_information(**kwargs)
        elif action == "get_scan_result_summary":
            return client.get_scan_result_summary(**kwargs)
        elif action == "get_cookies_by_filter":
            return client.get_cookies_by_filter(**kwargs)
        elif action == "check_scans_status":
            return client.check_scans_status(**kwargs)
        elif action == "cancel_scan":
            return client.cancel_scan(**kwargs)
        elif action == "recategorize_cookies_by_scan":
            return client.recategorize_cookies_by_scan(**kwargs)
        raise ValueError(f"Unknown action: {action}")
