"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_task_management_tools(mcp: FastMCP):
    @mcp.tool(tags={"task_management"})
    async def onetrust_task_management(
        action: str = Field(
            description="Action to perform. One of: 'create_task_using_post', 'get_task_by_id_and_task_type_name_key_using_get', 'update_task_using_put'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust task management operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_task_management action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "create_task_using_post":
            return client.create_task_using_post(**kwargs)
        elif action == "get_task_by_id_and_task_type_name_key_using_get":
            return client.get_task_by_id_and_task_type_name_key_using_get(**kwargs)
        elif action == "update_task_using_put":
            return client.update_task_using_put(**kwargs)
        raise ValueError(f"Unknown action: {action}")

