"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_tprm_tools(mcp: FastMCP):
    @mcp.tool(tags={"tprm"})
    async def onetrust_tprm(
        action: str = Field(
            description="Action to perform. One of: 'create_vendor_contract_using_post', 'get_contract_schema_using_get', 'fetch_all_contract_types_using_get', 'search_contract_by_vendor_and_criteria_using_post', 'remove_vendor_contract_using_delete', 'load_vendor_contract_by_contract_id_using_get', 'update_vendor_contract_using_put', 'get_engagement_schema_using_get', 'load_engagement_by_engagement_id_using_get', 'update_engagement_using_put', 'remove_engagement_using_delete', 'update_engagement_using_patch', 'update_engagement_status', 'load_engagement_using_get', 'create_engagement_using_post'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust tprm operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_tprm action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "create_vendor_contract_using_post":
            return client.create_vendor_contract_using_post(**kwargs)
        elif action == "get_contract_schema_using_get":
            return client.get_contract_schema_using_get(**kwargs)
        elif action == "fetch_all_contract_types_using_get":
            return client.fetch_all_contract_types_using_get(**kwargs)
        elif action == "search_contract_by_vendor_and_criteria_using_post":
            return client.search_contract_by_vendor_and_criteria_using_post(**kwargs)
        elif action == "remove_vendor_contract_using_delete":
            return client.remove_vendor_contract_using_delete(**kwargs)
        elif action == "load_vendor_contract_by_contract_id_using_get":
            return client.load_vendor_contract_by_contract_id_using_get(**kwargs)
        elif action == "update_vendor_contract_using_put":
            return client.update_vendor_contract_using_put(**kwargs)
        elif action == "get_engagement_schema_using_get":
            return client.get_engagement_schema_using_get(**kwargs)
        elif action == "load_engagement_by_engagement_id_using_get":
            return client.load_engagement_by_engagement_id_using_get(**kwargs)
        elif action == "update_engagement_using_put":
            return client.update_engagement_using_put(**kwargs)
        elif action == "remove_engagement_using_delete":
            return client.remove_engagement_using_delete(**kwargs)
        elif action == "update_engagement_using_patch":
            return client.update_engagement_using_patch(**kwargs)
        elif action == "update_engagement_status":
            return client.update_engagement_status(**kwargs)
        elif action == "load_engagement_using_get":
            return client.load_engagement_using_get(**kwargs)
        elif action == "create_engagement_using_post":
            return client.create_engagement_using_post(**kwargs)
        raise ValueError(f"Unknown action: {action}")
