"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_inventory_tools(mcp: FastMCP):
    @mcp.tool(tags={"inventory"})
    async def onetrust_inventory(
        action: str = Field(
            description="Action to perform. One of: 'list_all_inventory_relationships_using_post', 'update_inventory_relations_using_entity_type_name_1', 'link_or_unlink_inventory_relationships_using_relationship_using_put_1', 'get_personal_data_for_relationships_using_post_1', 'update_inventory_relations_using_entity_type_name', 'link_or_unlink_inventory_relationships_using_relationship_using_put', 'get_personal_data_for_relationships_using_post', 'create_inventory_relations_using_post', 'add_relationship_between_entities_using_post', 'get_inventory_relationship_using_relationship_type_name_1', 'delete_inventory_relations_using_relationship_type_name_1', 'get_inventory_relationship_using_relationship_type_name', 'delete_inventory_relations_using_relationship_type_name'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust inventory operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_inventory action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "list_all_inventory_relationships_using_post":
            return client.list_all_inventory_relationships_using_post(**kwargs)
        elif action == "update_inventory_relations_using_entity_type_name_1":
            return client.update_inventory_relations_using_entity_type_name_1(**kwargs)
        elif action == "link_or_unlink_inventory_relationships_using_relationship_using_put_1":
            return client.link_or_unlink_inventory_relationships_using_relationship_using_put_1(**kwargs)
        elif action == "get_personal_data_for_relationships_using_post_1":
            return client.get_personal_data_for_relationships_using_post_1(**kwargs)
        elif action == "update_inventory_relations_using_entity_type_name":
            return client.update_inventory_relations_using_entity_type_name(**kwargs)
        elif action == "link_or_unlink_inventory_relationships_using_relationship_using_put":
            return client.link_or_unlink_inventory_relationships_using_relationship_using_put(**kwargs)
        elif action == "get_personal_data_for_relationships_using_post":
            return client.get_personal_data_for_relationships_using_post(**kwargs)
        elif action == "create_inventory_relations_using_post":
            return client.create_inventory_relations_using_post(**kwargs)
        elif action == "add_relationship_between_entities_using_post":
            return client.add_relationship_between_entities_using_post(**kwargs)
        elif action == "get_inventory_relationship_using_relationship_type_name_1":
            return client.get_inventory_relationship_using_relationship_type_name_1(**kwargs)
        elif action == "delete_inventory_relations_using_relationship_type_name_1":
            return client.delete_inventory_relations_using_relationship_type_name_1(**kwargs)
        elif action == "get_inventory_relationship_using_relationship_type_name":
            return client.get_inventory_relationship_using_relationship_type_name(**kwargs)
        elif action == "delete_inventory_relations_using_relationship_type_name":
            return client.delete_inventory_relations_using_relationship_type_name(**kwargs)
        raise ValueError(f"Unknown action: {action}")

