"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_privacy_notices_tools(mcp: FastMCP):
    @mcp.tool(tags={"privacy_notices"})
    async def onetrust_privacy_notices(
        action: str = Field(
            description="Action to perform. One of: 'get_privacy_notices_using_get', 'get_privacy_notice_version_by_published_date_using_get', 'get_privacy_notice_versions_using_get'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust privacy notices operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_privacy_notices action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_privacy_notices_using_get":
            return client.get_privacy_notices_using_get(**kwargs)
        elif action == "get_privacy_notice_version_by_published_date_using_get":
            return client.get_privacy_notice_version_by_published_date_using_get(**kwargs)
        elif action == "get_privacy_notice_versions_using_get":
            return client.get_privacy_notice_versions_using_get(**kwargs)
        raise ValueError(f"Unknown action: {action}")

