"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_audit_management_tools(mcp: FastMCP):
    @mcp.tool(tags={"audit_management"})
    async def onetrust_audit_management(
        action: str = Field(
            description="Action to perform. One of: 'delete_scope_using_delete', 'get_audit_workpaper_list_view_using_post', 'edit_workpaper_details_using_post', 'get_workpaper_result_using_get', 'get_workpaper_basic_detail_information_using_get', 'validate_and_create_audit_using_post', 'get_audit_list_page_using_post', 'get_audit_detail_using_get', 'validate_and_update_audit_using_put', 'delete_audit_using_delete', 'validate_and_reassign_scopes_using_put'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust audit management operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_audit_management action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "delete_scope_using_delete":
            return client.delete_scope_using_delete(**kwargs)
        elif action == "get_audit_workpaper_list_view_using_post":
            return client.get_audit_workpaper_list_view_using_post(**kwargs)
        elif action == "edit_workpaper_details_using_post":
            return client.edit_workpaper_details_using_post(**kwargs)
        elif action == "get_workpaper_result_using_get":
            return client.get_workpaper_result_using_get(**kwargs)
        elif action == "get_workpaper_basic_detail_information_using_get":
            return client.get_workpaper_basic_detail_information_using_get(**kwargs)
        elif action == "validate_and_create_audit_using_post":
            return client.validate_and_create_audit_using_post(**kwargs)
        elif action == "get_audit_list_page_using_post":
            return client.get_audit_list_page_using_post(**kwargs)
        elif action == "get_audit_detail_using_get":
            return client.get_audit_detail_using_get(**kwargs)
        elif action == "validate_and_update_audit_using_put":
            return client.validate_and_update_audit_using_put(**kwargs)
        elif action == "delete_audit_using_delete":
            return client.delete_audit_using_delete(**kwargs)
        elif action == "validate_and_reassign_scopes_using_put":
            return client.validate_and_reassign_scopes_using_put(**kwargs)
        raise ValueError(f"Unknown action: {action}")
