"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client

_UNHANDLED = object()


def _dispatch_policy_management_1(action, kwargs, client):
    # create_policy .. create_policy_versions (6 actions)
    if action == "create_policy":
        return client.create_policy(**kwargs)
    elif action == "get_latest_policies":
        return client.get_latest_policies(**kwargs)
    elif action == "get_policy":
        return client.get_policy(**kwargs)
    elif action == "get_published_policy_version":
        return client.get_published_policy_version(**kwargs)
    elif action == "add_document_to_policy":
        return client.add_document_to_policy(**kwargs)
    elif action == "create_policy_versions":
        return client.create_policy_versions(**kwargs)
    return _UNHANDLED


_POLICY_MANAGEMENT_DISPATCHERS = (_dispatch_policy_management_1,)


def register_policy_management_tools(mcp: FastMCP):
    @mcp.tool(tags={"policy_management"})
    async def onetrust_policy_management(
        action: str = Field(
            description="Action to perform. One of: 'create_policy', 'get_latest_policies', 'get_policy', 'get_published_policy_version', 'add_document_to_policy', 'create_policy_versions'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust policy management operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_policy_management action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {type(e).__name__}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        for _dispatch in _POLICY_MANAGEMENT_DISPATCHERS:
            _result = _dispatch(action, kwargs, client)
            if _result is not _UNHANDLED:
                return _result
        raise ValueError(f"Unknown action: {action}")
