"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_user_provisioning_tools(mcp: FastMCP):
    @mcp.tool(tags={"user_provisioning"})
    async def onetrust_user_provisioning(
        action: str = Field(
            description="Action to perform. One of: 'list_groups_using_get', 'get_group_resource_using_get', 'update_group_members_using_put', 'update_group_members_using_patch', 'get_all_users_using_get', 'create_user_using_post', 'get_user_using_get', 'update_user_using_put', 'delete_user_using_delete', 'patch_user_using_patch', 'get_groups', 'create_group', 'get_group_by_id', 'update_group', 'delete_group', 'modify_group', 'get_resource_types_using_get', 'get_resource_types_by_name_using_get', 'get_schemas_using_get', 'get_schemas_by_name_using_get', 'get_service_provider_config_using_get', 'get_users', 'create_user', 'get_user_by_id', 'update_user', 'modify_user'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust user provisioning operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_user_provisioning action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "list_groups_using_get":
            return client.list_groups_using_get(**kwargs)
        elif action == "get_group_resource_using_get":
            return client.get_group_resource_using_get(**kwargs)
        elif action == "update_group_members_using_put":
            return client.update_group_members_using_put(**kwargs)
        elif action == "update_group_members_using_patch":
            return client.update_group_members_using_patch(**kwargs)
        elif action == "get_all_users_using_get":
            return client.get_all_users_using_get(**kwargs)
        elif action == "create_user_using_post":
            return client.create_user_using_post(**kwargs)
        elif action == "get_user_using_get":
            return client.get_user_using_get(**kwargs)
        elif action == "update_user_using_put":
            return client.update_user_using_put(**kwargs)
        elif action == "delete_user_using_delete":
            return client.delete_user_using_delete(**kwargs)
        elif action == "patch_user_using_patch":
            return client.patch_user_using_patch(**kwargs)
        elif action == "get_groups":
            return client.get_groups(**kwargs)
        elif action == "create_group":
            return client.create_group(**kwargs)
        elif action == "get_group_by_id":
            return client.get_group_by_id(**kwargs)
        elif action == "update_group":
            return client.update_group(**kwargs)
        elif action == "delete_group":
            return client.delete_group(**kwargs)
        elif action == "modify_group":
            return client.modify_group(**kwargs)
        elif action == "get_resource_types_using_get":
            return client.get_resource_types_using_get(**kwargs)
        elif action == "get_resource_types_by_name_using_get":
            return client.get_resource_types_by_name_using_get(**kwargs)
        elif action == "get_schemas_using_get":
            return client.get_schemas_using_get(**kwargs)
        elif action == "get_schemas_by_name_using_get":
            return client.get_schemas_by_name_using_get(**kwargs)
        elif action == "get_service_provider_config_using_get":
            return client.get_service_provider_config_using_get(**kwargs)
        elif action == "get_users":
            return client.get_users(**kwargs)
        elif action == "create_user":
            return client.create_user(**kwargs)
        elif action == "get_user_by_id":
            return client.get_user_by_id(**kwargs)
        elif action == "update_user":
            return client.update_user(**kwargs)
        elif action == "modify_user":
            return client.modify_user(**kwargs)
        raise ValueError(f"Unknown action: {action}")

