"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client

_UNHANDLED = object()


def _dispatch_cmp_1(action, kwargs, client):
    # get_banner .. get_vendors (5 actions)
    if action == "get_banner":
        return client.get_banner(**kwargs)
    elif action == "get_preferences":
        return client.get_preferences(**kwargs)
    elif action == "post_log_consent":
        return client.post_log_consent(**kwargs)
    elif action == "get_ucpurposes":
        return client.get_ucpurposes(**kwargs)
    elif action == "get_vendors":
        return client.get_vendors(**kwargs)
    return _UNHANDLED


_CMP_DISPATCHERS = (_dispatch_cmp_1,)


def register_cmp_tools(mcp: FastMCP):
    @mcp.tool(tags={"cmp"})
    async def onetrust_cmp(
        action: str = Field(
            description="Action to perform. One of: 'get_banner', 'get_preferences', 'post_log_consent', 'get_ucpurposes', 'get_vendors'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust cmp operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_cmp action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {type(e).__name__}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        for _dispatch in _CMP_DISPATCHERS:
            _result = _dispatch(action, kwargs, client)
            if _result is not _UNHANDLED:
                return _result
        raise ValueError(f"Unknown action: {action}")
