"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_data_discovery_tools(mcp: FastMCP):
    @mcp.tool(tags={"data_discovery"})
    async def onetrust_data_discovery(
        action: str = Field(
            description="Action to perform. One of: 'get_credentials', 'update_credential', 'create_credential', 'get_credential_by_id', 'delete_credential', 'create_job_using_post', 'get_scan_jobs_by_data_source_using_get_1', 'get_job_by_id_using_get', 'cancel_job_using_patch', 'get_all_using_get_2', 'update_v2_using_put', 'create_v2_using_post', 'get_scan_profile_using_get_1', 'delete_scan_profile_using_delete_1', 'get_job_using_get_1', 'cancel_scan_job', 'get_docker_repository_tags_using_get', 'get_all_using_get_1', 'upsert_source_system_v3_using_put', 'get_data_source_by_id_using_get_1', 'delete_system_using_delete_1', 'list_detectors', 'create_detector', 'get_detector_by_classifier_name', 'update_detector', 'delete_detector'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust data discovery operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_data_discovery action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_credentials":
            return client.get_credentials(**kwargs)
        elif action == "update_credential":
            return client.update_credential(**kwargs)
        elif action == "create_credential":
            return client.create_credential(**kwargs)
        elif action == "get_credential_by_id":
            return client.get_credential_by_id(**kwargs)
        elif action == "delete_credential":
            return client.delete_credential(**kwargs)
        elif action == "create_job_using_post":
            return client.create_job_using_post_x(**kwargs)
        elif action == "get_scan_jobs_by_data_source_using_get_1":
            return client.get_scan_jobs_by_data_source_using_get_1(**kwargs)
        elif action == "get_job_by_id_using_get":
            return client.get_job_by_id_using_get(**kwargs)
        elif action == "cancel_job_using_patch":
            return client.cancel_job_using_patch(**kwargs)
        elif action == "get_all_using_get_2":
            return client.get_all_using_get_2(**kwargs)
        elif action == "update_v2_using_put":
            return client.update_v2_using_put(**kwargs)
        elif action == "create_v2_using_post":
            return client.create_v2_using_post(**kwargs)
        elif action == "get_scan_profile_using_get_1":
            return client.get_scan_profile_using_get_1(**kwargs)
        elif action == "delete_scan_profile_using_delete_1":
            return client.delete_scan_profile_using_delete_1(**kwargs)
        elif action == "get_job_using_get_1":
            return client.get_job_using_get_1(**kwargs)
        elif action == "cancel_scan_job":
            return client.cancel_scan_job(**kwargs)
        elif action == "get_docker_repository_tags_using_get":
            return client.get_docker_repository_tags_using_get(**kwargs)
        elif action == "get_all_using_get_1":
            return client.get_all_using_get_1(**kwargs)
        elif action == "upsert_source_system_v3_using_put":
            return client.upsert_source_system_v3_using_put(**kwargs)
        elif action == "get_data_source_by_id_using_get_1":
            return client.get_data_source_by_id_using_get_1(**kwargs)
        elif action == "delete_system_using_delete_1":
            return client.delete_system_using_delete_1(**kwargs)
        elif action == "list_detectors":
            return client.list_detectors(**kwargs)
        elif action == "create_detector":
            return client.create_detector(**kwargs)
        elif action == "get_detector_by_classifier_name":
            return client.get_detector_by_classifier_name(**kwargs)
        elif action == "update_detector":
            return client.update_detector(**kwargs)
        elif action == "delete_detector":
            return client.delete_detector(**kwargs)
        raise ValueError(f"Unknown action: {action}")

