"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_data_mapping_tools(mcp: FastMCP):
    @mcp.tool(tags={"data_mapping"})
    async def onetrust_data_mapping(
        action: str = Field(
            description="Action to perform. One of: 'get_data_categories_by_partial_name_using_get', 'create_data_category_using_post', 'get_data_category_using_get', 'delete_data_category_using_delete', 'create_data_classification_using_post', 'get_data_classification_using_get', 'delete_data_classification_using_delete', 'create_data_element_using_post', 'get_data_element_using_get', 'delete_data_element_using_delete', 'get_data_subjects_by_partial_name_using_get', 'create_data_subject_using_post', 'get_data_subject_using_get', 'delete_data_subject_using_delete', 'update_inventory_association_using_put', 'update_relations_using_put', 'create_relations_using_post', 'delete_relations_using_delete', 'get_inventory_relations_by_id_using_get', 'set_inventory_as_parent_inventory_using_put', 'unset_inventory_as_parent_inventory_using_put', 'link_asset_inventory_to_parent_asset_id_using_post', 'link_legal_entity_inventory_to_parent_legal_entity_id_using_post', 'link_processing_activity_inventory_to_parent_processing_activity_id_using_post', 'link_vendor_inventory_to_parent_vendor_id_using_post', 'get_list_of_inventories_using_get', 'create_inventory_using_post', 'upsert_inventory_using_put', 'get_list_of_inventories_by_filter_criteria_using_post', 'get_inventory_by_external_id_using_get', 'get_inventory_by_id_using_get', 'update_inventory_using_put', 'delete_inventory_using_delete', 'copy_inventory_using_post', 'update_inventory_status_by_id_using_put', 'add_controls_to_inventory_using_post', 'update_advanced_attributes_for_personal_data_association_using_put', 'get_hierarchy_for_inventory_id_using_get', 'unlink_child_inventory_from_hierarchy_using_delete', 'get_all_schemas_using_get', 'get_schema_details_using_field_name'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust data mapping operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_data_mapping action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_data_categories_by_partial_name_using_get":
            return client.get_data_categories_by_partial_name_using_get(**kwargs)
        elif action == "create_data_category_using_post":
            return client.create_data_category_using_post(**kwargs)
        elif action == "get_data_category_using_get":
            return client.get_data_category_using_get(**kwargs)
        elif action == "delete_data_category_using_delete":
            return client.delete_data_category_using_delete(**kwargs)
        elif action == "create_data_classification_using_post":
            return client.create_data_classification_using_post(**kwargs)
        elif action == "get_data_classification_using_get":
            return client.get_data_classification_using_get(**kwargs)
        elif action == "delete_data_classification_using_delete":
            return client.delete_data_classification_using_delete(**kwargs)
        elif action == "create_data_element_using_post":
            return client.create_data_element_using_post(**kwargs)
        elif action == "get_data_element_using_get":
            return client.get_data_element_using_get(**kwargs)
        elif action == "delete_data_element_using_delete":
            return client.delete_data_element_using_delete(**kwargs)
        elif action == "get_data_subjects_by_partial_name_using_get":
            return client.get_data_subjects_by_partial_name_using_get(**kwargs)
        elif action == "create_data_subject_using_post":
            return client.create_data_subject_using_post(**kwargs)
        elif action == "get_data_subject_using_get":
            return client.get_data_subject_using_get(**kwargs)
        elif action == "delete_data_subject_using_delete":
            return client.delete_data_subject_using_delete(**kwargs)
        elif action == "update_inventory_association_using_put":
            return client.update_inventory_association_using_put(**kwargs)
        elif action == "update_relations_using_put":
            return client.update_relations_using_put(**kwargs)
        elif action == "create_relations_using_post":
            return client.create_relations_using_post(**kwargs)
        elif action == "delete_relations_using_delete":
            return client.delete_relations_using_delete(**kwargs)
        elif action == "get_inventory_relations_by_id_using_get":
            return client.get_inventory_relations_by_id_using_get(**kwargs)
        elif action == "set_inventory_as_parent_inventory_using_put":
            return client.set_inventory_as_parent_inventory_using_put(**kwargs)
        elif action == "unset_inventory_as_parent_inventory_using_put":
            return client.unset_inventory_as_parent_inventory_using_put(**kwargs)
        elif action == "link_asset_inventory_to_parent_asset_id_using_post":
            return client.link_asset_inventory_to_parent_asset_id_using_post(**kwargs)
        elif (
            action == "link_legal_entity_inventory_to_parent_legal_entity_id_using_post"
        ):
            return (
                client.link_legal_entity_inventory_to_parent_legal_entity_id_using_post(
                    **kwargs
                )
            )
        elif (
            action
            == "link_processing_activity_inventory_to_parent_processing_activity_id_using_post"
        ):
            return client.link_processing_activity_inventory_to_parent_processing_activity_id_using_post(
                **kwargs
            )
        elif action == "link_vendor_inventory_to_parent_vendor_id_using_post":
            return client.link_vendor_inventory_to_parent_vendor_id_using_post(**kwargs)
        elif action == "get_list_of_inventories_using_get":
            return client.get_list_of_inventories_using_get(**kwargs)
        elif action == "create_inventory_using_post":
            return client.create_inventory_using_post(**kwargs)
        elif action == "upsert_inventory_using_put":
            return client.upsert_inventory_using_put(**kwargs)
        elif action == "get_list_of_inventories_by_filter_criteria_using_post":
            return client.get_list_of_inventories_by_filter_criteria_using_post(
                **kwargs
            )
        elif action == "get_inventory_by_external_id_using_get":
            return client.get_inventory_by_external_id_using_get(**kwargs)
        elif action == "get_inventory_by_id_using_get":
            return client.get_inventory_by_id_using_get(**kwargs)
        elif action == "update_inventory_using_put":
            return client.update_inventory_using_put(**kwargs)
        elif action == "delete_inventory_using_delete":
            return client.delete_inventory_using_delete(**kwargs)
        elif action == "copy_inventory_using_post":
            return client.copy_inventory_using_post(**kwargs)
        elif action == "update_inventory_status_by_id_using_put":
            return client.update_inventory_status_by_id_using_put(**kwargs)
        elif action == "add_controls_to_inventory_using_post":
            return client.add_controls_to_inventory_using_post(**kwargs)
        elif (
            action
            == "update_advanced_attributes_for_personal_data_association_using_put"
        ):
            return client.update_advanced_attributes_for_personal_data_association_using_put(
                **kwargs
            )
        elif action == "get_hierarchy_for_inventory_id_using_get":
            return client.get_hierarchy_for_inventory_id_using_get(**kwargs)
        elif action == "unlink_child_inventory_from_hierarchy_using_delete":
            return client.unlink_child_inventory_from_hierarchy_using_delete(**kwargs)
        elif action == "get_all_schemas_using_get":
            return client.get_all_schemas_using_get(**kwargs)
        elif action == "get_schema_details_using_field_name":
            return client.get_schema_details_using_field_name(**kwargs)
        raise ValueError(f"Unknown action: {action}")
