"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_integrations_tools(mcp: FastMCP):
    @mcp.tool(tags={"integrations"})
    async def onetrust_integrations(
        action: str = Field(
            description="Action to perform. One of: 'update_v2_using_put', 'create_v2_using_post', 'export_workflow_using_get_1', 'import_workflow_using_post_1'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust integrations operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_integrations action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "update_v2_using_put":
            return client.update_v2_using_put_x(**kwargs)
        elif action == "create_v2_using_post":
            return client.create_v2_using_post_x(**kwargs)
        elif action == "export_workflow_using_get_1":
            return client.export_workflow_using_get_1(**kwargs)
        elif action == "import_workflow_using_post_1":
            return client.import_workflow_using_post_1(**kwargs)
        raise ValueError(f"Unknown action: {action}")

