"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_bulk_export_tools(mcp: FastMCP):
    @mcp.tool(tags={"bulk_export"})
    async def onetrust_bulk_export(
        action: str = Field(
            description="Action to perform. One of: 'get_export_runs_get', 'start_export_run_post', 'get_credits_information_get', 'get_export_run_details_get', 'cancel_bulk_export_delete', 'get_attachment_download_commands_get', 'get_paginated_attachment_download_commands_get'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust bulk export operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_bulk_export action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_export_runs_get":
            return client.get_export_runs_get(**kwargs)
        elif action == "start_export_run_post":
            return client.start_export_run_post(**kwargs)
        elif action == "get_credits_information_get":
            return client.get_credits_information_get(**kwargs)
        elif action == "get_export_run_details_get":
            return client.get_export_run_details_get(**kwargs)
        elif action == "cancel_bulk_export_delete":
            return client.cancel_bulk_export_delete(**kwargs)
        elif action == "get_attachment_download_commands_get":
            return client.get_attachment_download_commands_get(**kwargs)
        elif action == "get_paginated_attachment_download_commands_get":
            return client.get_paginated_attachment_download_commands_get(**kwargs)
        raise ValueError(f"Unknown action: {action}")
