"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_data_mapping_legacy_tools(mcp: FastMCP):
    @mcp.tool(tags={"data_mapping_legacy"})
    async def onetrust_data_mapping_legacy(
        action: str = Field(
            description="Action to perform. One of: 'list_all_data_classifications_using_get', 'list_all_data_elements_using_get', 'get_schema_using_get_1', 'get_inventory_v2_schemas_attributes_attribute_id_values_value_id'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust data mapping legacy operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_data_mapping_legacy action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "list_all_data_classifications_using_get":
            return client.list_all_data_classifications_using_get(**kwargs)
        elif action == "list_all_data_elements_using_get":
            return client.list_all_data_elements_using_get(**kwargs)
        elif action == "get_schema_using_get_1":
            return client.get_schema_using_get_1(**kwargs)
        elif action == "get_inventory_v2_schemas_attributes_attribute_id_values_value_id":
            return client.get_inventory_v2_schemas_attributes_attribute_id_values_value_id(**kwargs)
        raise ValueError(f"Unknown action: {action}")

