"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_cookie_consent_legacy_tools(mcp: FastMCP):
    @mcp.tool(tags={"cookie_consent_legacy"})
    async def onetrust_cookie_consent_legacy(
        action: str = Field(
            description="Action to perform. One of: 'download_to_local_using_get', 'request_bulk_add_domain_using_post', 'get_domains_scanned_by_sort_using_get', 'get_script_for_website_using_get', 'publish_to_site_using_put', 'create_new_cookie', 'update_cookie', 'get_categorized_cookies_using_get', 'get_categorized_cookies_with_cookie_ids_using_get', 'create_domain_group_using_post', 'get_cookie_reports_using_post'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust cookie consent legacy operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_cookie_consent_legacy action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "download_to_local_using_get":
            return client.download_to_local_using_get(**kwargs)
        elif action == "request_bulk_add_domain_using_post":
            return client.request_bulk_add_domain_using_post(**kwargs)
        elif action == "get_domains_scanned_by_sort_using_get":
            return client.get_domains_scanned_by_sort_using_get(**kwargs)
        elif action == "get_script_for_website_using_get":
            return client.get_script_for_website_using_get(**kwargs)
        elif action == "publish_to_site_using_put":
            return client.publish_to_site_using_put(**kwargs)
        elif action == "create_new_cookie":
            return client.create_new_cookie(**kwargs)
        elif action == "update_cookie":
            return client.update_cookie(**kwargs)
        elif action == "get_categorized_cookies_using_get":
            return client.get_categorized_cookies_using_get(**kwargs)
        elif action == "get_categorized_cookies_with_cookie_ids_using_get":
            return client.get_categorized_cookies_with_cookie_ids_using_get(**kwargs)
        elif action == "create_domain_group_using_post":
            return client.create_domain_group_using_post(**kwargs)
        elif action == "get_cookie_reports_using_post":
            return client.get_cookie_reports_using_post(**kwargs)
        raise ValueError(f"Unknown action: {action}")
