"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client

_UNHANDLED = object()


def _dispatch_cookie_domain_data_1(action, kwargs, client):
    # domaindata .. domaindata (1 actions)
    if action == "domaindata":
        return client.domaindata(**kwargs)
    return _UNHANDLED


_COOKIE_DOMAIN_DATA_DISPATCHERS = (_dispatch_cookie_domain_data_1,)


def register_cookie_domain_data_tools(mcp: FastMCP):
    @mcp.tool(tags={"cookie_domain_data"})
    async def onetrust_cookie_domain_data(
        action: str = Field(description="Action to perform. One of: 'domaindata'"),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust cookie domain data operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_cookie_domain_data action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {type(e).__name__}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        for _dispatch in _COOKIE_DOMAIN_DATA_DISPATCHERS:
            _result = _dispatch(action, kwargs, client)
            if _result is not _UNHANDLED:
                return _result
        raise ValueError(f"Unknown action: {action}")
