"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_data_catalog_tools(mcp: FastMCP):
    @mcp.tool(tags={"data_catalog"})
    async def onetrust_data_catalog(
        action: str = Field(
            description="Action to perform. One of: 'get_all_glossaries_names', 'get_all_glossaries_by_names', 'retrieve_all_tags_name', 'get_tag_details_with_associated_terms', 'retrieve_all_terms', 'get_term_attribute_by_name', 'get_all_term_attribute_names', 'retrieve_terms_by_name', 'retrieve_terms_name', 'create_tag_v2', 'create_term_using_post', 'create_or_upsert_data_asset_v1', 'get_data_asset_v1', 'delete_data_asset_v1', 'update_data_asset_v1', 'create_data_asset_tag_associations_v1', 'delete_data_asset_tag_associations_v1', 'create_data_asset_term_associations_v1', 'delete_data_asset_term_associations_v1', 'get_data_asset_attribute_by_name', 'get_all_data_asset_attribute_names', 'external_search', 'get_v1_field_details', 'external_search_using_continuationtoken'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust data catalog operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_data_catalog action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_all_glossaries_names":
            return client.get_all_glossaries_names(**kwargs)
        elif action == "get_all_glossaries_by_names":
            return client.get_all_glossaries_by_names(**kwargs)
        elif action == "retrieve_all_tags_name":
            return client.retrieve_all_tags_name(**kwargs)
        elif action == "get_tag_details_with_associated_terms":
            return client.get_tag_details_with_associated_terms(**kwargs)
        elif action == "retrieve_all_terms":
            return client.retrieve_all_terms(**kwargs)
        elif action == "get_term_attribute_by_name":
            return client.get_term_attribute_by_name(**kwargs)
        elif action == "get_all_term_attribute_names":
            return client.get_all_term_attribute_names(**kwargs)
        elif action == "retrieve_terms_by_name":
            return client.retrieve_terms_by_name(**kwargs)
        elif action == "retrieve_terms_name":
            return client.retrieve_terms_name(**kwargs)
        elif action == "create_tag_v2":
            return client.create_tag_v2(**kwargs)
        elif action == "create_term_using_post":
            return client.create_term_using_post(**kwargs)
        elif action == "create_or_upsert_data_asset_v1":
            return client.create_or_upsert_data_asset_v1(**kwargs)
        elif action == "get_data_asset_v1":
            return client.get_data_asset_v1(**kwargs)
        elif action == "delete_data_asset_v1":
            return client.delete_data_asset_v1(**kwargs)
        elif action == "update_data_asset_v1":
            return client.update_data_asset_v1(**kwargs)
        elif action == "create_data_asset_tag_associations_v1":
            return client.create_data_asset_tag_associations_v1(**kwargs)
        elif action == "delete_data_asset_tag_associations_v1":
            return client.delete_data_asset_tag_associations_v1(**kwargs)
        elif action == "create_data_asset_term_associations_v1":
            return client.create_data_asset_term_associations_v1(**kwargs)
        elif action == "delete_data_asset_term_associations_v1":
            return client.delete_data_asset_term_associations_v1(**kwargs)
        elif action == "get_data_asset_attribute_by_name":
            return client.get_data_asset_attribute_by_name(**kwargs)
        elif action == "get_all_data_asset_attribute_names":
            return client.get_all_data_asset_attribute_names(**kwargs)
        elif action == "external_search":
            return client.external_search(**kwargs)
        elif action == "get_v1_field_details":
            return client.get_v1_field_details(**kwargs)
        elif action == "external_search_using_continuationtoken":
            return client.external_search_using_continuationtoken(**kwargs)
        raise ValueError(f"Unknown action: {action}")

