"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_assessments_tools(mcp: FastMCP):
    @mcp.tool(tags={"assessments"})
    async def onetrust_assessments(
        action: str = Field(
            description="Action to perform. One of: 'review_assessment_using_post', 'get_tags_using_get', 'get_all_assessment_basic_details_using_get', 'create_assessment_using_post_1', 'get_assessment_delete_logs_using_get', 'archive_assessments_using_put', 'add_manual_assessment_links_using_post', 'get_assessment_results_using_get', 'create_bulk_assessment_using_post', 'get_linked_assessments_information_using_get', 'unarchive_assessments_using_put', 'export_assessment_using_get', 'update_basic_assessment_details_using_patch', 'update_primary_record_using_put', 'reassign_assessment_using_put', 'submit_responses_using_post', 'create_assessment_risk_using_post', 'soft_delete_assessment_using_put', 'submit_assessment_using_post', 'add_or_update_tags_using_put', 'create_task_using_post', 'get_workflow_details_for_assessment_using_get', 'reassess_assessment_using_post', 'reopen_assessment_using_post', 'send_back_assessment_to_in_progress_using_post', 'create_assessment_using_post', 'get_assessments_using_post', 'approve_assessment_using_post', 'get_all_basic_template_details_using_get', 'import_template_by_id_using_post', 'delete_template_versions_using_delete', 'export_template_with_business_keys_using_get'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust assessments operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_assessments action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "review_assessment_using_post":
            return client.review_assessment_using_post(**kwargs)
        elif action == "get_tags_using_get":
            return client.get_tags_using_get(**kwargs)
        elif action == "get_all_assessment_basic_details_using_get":
            return client.get_all_assessment_basic_details_using_get(**kwargs)
        elif action == "create_assessment_using_post_1":
            return client.create_assessment_using_post_1(**kwargs)
        elif action == "get_assessment_delete_logs_using_get":
            return client.get_assessment_delete_logs_using_get(**kwargs)
        elif action == "archive_assessments_using_put":
            return client.archive_assessments_using_put(**kwargs)
        elif action == "add_manual_assessment_links_using_post":
            return client.add_manual_assessment_links_using_post(**kwargs)
        elif action == "get_assessment_results_using_get":
            return client.get_assessment_results_using_get(**kwargs)
        elif action == "create_bulk_assessment_using_post":
            return client.create_bulk_assessment_using_post(**kwargs)
        elif action == "get_linked_assessments_information_using_get":
            return client.get_linked_assessments_information_using_get(**kwargs)
        elif action == "unarchive_assessments_using_put":
            return client.unarchive_assessments_using_put(**kwargs)
        elif action == "export_assessment_using_get":
            return client.export_assessment_using_get(**kwargs)
        elif action == "update_basic_assessment_details_using_patch":
            return client.update_basic_assessment_details_using_patch(**kwargs)
        elif action == "update_primary_record_using_put":
            return client.update_primary_record_using_put(**kwargs)
        elif action == "reassign_assessment_using_put":
            return client.reassign_assessment_using_put(**kwargs)
        elif action == "submit_responses_using_post":
            return client.submit_responses_using_post(**kwargs)
        elif action == "create_assessment_risk_using_post":
            return client.create_assessment_risk_using_post(**kwargs)
        elif action == "soft_delete_assessment_using_put":
            return client.soft_delete_assessment_using_put(**kwargs)
        elif action == "submit_assessment_using_post":
            return client.submit_assessment_using_post(**kwargs)
        elif action == "add_or_update_tags_using_put":
            return client.add_or_update_tags_using_put(**kwargs)
        elif action == "create_task_using_post":
            return client.create_task_using_post_x(**kwargs)
        elif action == "get_workflow_details_for_assessment_using_get":
            return client.get_workflow_details_for_assessment_using_get(**kwargs)
        elif action == "reassess_assessment_using_post":
            return client.reassess_assessment_using_post(**kwargs)
        elif action == "reopen_assessment_using_post":
            return client.reopen_assessment_using_post(**kwargs)
        elif action == "send_back_assessment_to_in_progress_using_post":
            return client.send_back_assessment_to_in_progress_using_post(**kwargs)
        elif action == "create_assessment_using_post":
            return client.create_assessment_using_post(**kwargs)
        elif action == "get_assessments_using_post":
            return client.get_assessments_using_post(**kwargs)
        elif action == "approve_assessment_using_post":
            return client.approve_assessment_using_post(**kwargs)
        elif action == "get_all_basic_template_details_using_get":
            return client.get_all_basic_template_details_using_get(**kwargs)
        elif action == "import_template_by_id_using_post":
            return client.import_template_by_id_using_post(**kwargs)
        elif action == "delete_template_versions_using_delete":
            return client.delete_template_versions_using_delete(**kwargs)
        elif action == "export_template_with_business_keys_using_get":
            return client.export_template_with_business_keys_using_get(**kwargs)
        raise ValueError(f"Unknown action: {action}")

