"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_data_discovery_worker_tools(mcp: FastMCP):
    @mcp.tool(tags={"data_discovery_worker"})
    async def onetrust_data_discovery_worker(
        action: str = Field(
            description="Action to perform. One of: 'get_eligible_jobs_using_get', 'catalog_data_using_post', 'classify_data_using_post', 'update_job_status_using_put'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust data discovery worker operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_data_discovery_worker action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_eligible_jobs_using_get":
            return client.get_eligible_jobs_using_get(**kwargs)
        elif action == "catalog_data_using_post":
            return client.catalog_data_using_post(**kwargs)
        elif action == "classify_data_using_post":
            return client.classify_data_using_post(**kwargs)
        elif action == "update_job_status_using_put":
            return client.update_job_status_using_put(**kwargs)
        raise ValueError(f"Unknown action: {action}")
