"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from onetrust_api.auth import get_client


def register_esg_tools(mcp: FastMCP):
    @mcp.tool(tags={"esg"})
    async def onetrust_esg(
        action: str = Field(
            description="Action to perform. One of: 'get_all_emission_factors_basic_entity_details', 'add_emission_factor', 'add_emission_transaction', 'find_all_by_type_and_criteria', 'fetch_metrics_details'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage OneTrust esg operations."""
        if ctx:
            await ctx.info(f"Executing onetrust_esg action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "get_all_emission_factors_basic_entity_details":
            return client.get_all_emission_factors_basic_entity_details(**kwargs)
        elif action == "add_emission_factor":
            return client.add_emission_factor(**kwargs)
        elif action == "add_emission_transaction":
            return client.add_emission_transaction(**kwargs)
        elif action == "find_all_by_type_and_criteria":
            return client.find_all_by_type_and_criteria(**kwargs)
        elif action == "fetch_metrics_details":
            return client.fetch_metrics_details(**kwargs)
        raise ValueError(f"Unknown action: {action}")

