#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_access_management import OneTrustAccessManagement
from onetrust_api.api.api_client_ai_governance import OneTrustAiGovernance
from onetrust_api.api.api_client_assessments import OneTrustAssessments
from onetrust_api.api.api_client_audit_management import OneTrustAuditManagement
from onetrust_api.api.api_client_bulk_export import OneTrustBulkExport
from onetrust_api.api.api_client_cmp import OneTrustCmp
from onetrust_api.api.api_client_compliance_automation import (
    OneTrustComplianceAutomation,
)
from onetrust_api.api.api_client_consent_interfaces import OneTrustConsentInterfaces
from onetrust_api.api.api_client_consent_receipts import OneTrustConsentReceipts
from onetrust_api.api.api_client_cookie_consent import OneTrustCookieConsent
from onetrust_api.api.api_client_cookie_consent_legacy import (
    OneTrustCookieConsentLegacy,
)
from onetrust_api.api.api_client_cookie_domain_data import OneTrustCookieDomainData
from onetrust_api.api.api_client_cross_device_consent import OneTrustCrossDeviceConsent
from onetrust_api.api.api_client_data_catalog import OneTrustDataCatalog
from onetrust_api.api.api_client_data_discovery import OneTrustDataDiscovery
from onetrust_api.api.api_client_data_discovery_worker import (
    OneTrustDataDiscoveryWorker,
)
from onetrust_api.api.api_client_data_mapping import OneTrustDataMapping
from onetrust_api.api.api_client_data_mapping_legacy import OneTrustDataMappingLegacy
from onetrust_api.api.api_client_documents import OneTrustDocuments
from onetrust_api.api.api_client_dsar import OneTrustDsar
from onetrust_api.api.api_client_esg import OneTrustEsg
from onetrust_api.api.api_client_incidents import OneTrustIncidents
from onetrust_api.api.api_client_integrations import OneTrustIntegrations
from onetrust_api.api.api_client_inventory import OneTrustInventory
from onetrust_api.api.api_client_issues_management import OneTrustIssuesManagement
from onetrust_api.api.api_client_it_risk_management import OneTrustItRiskManagement
from onetrust_api.api.api_client_mobile_app_consent import OneTrustMobileAppConsent
from onetrust_api.api.api_client_object_manager import OneTrustObjectManager
from onetrust_api.api.api_client_policy_management import OneTrustPolicyManagement
from onetrust_api.api.api_client_privacy_notices import OneTrustPrivacyNotices
from onetrust_api.api.api_client_task_management import OneTrustTaskManagement
from onetrust_api.api.api_client_tprm import OneTrustTprm
from onetrust_api.api.api_client_training import OneTrustTraining
from onetrust_api.api.api_client_universal_consent import OneTrustUniversalConsent
from onetrust_api.api.api_client_user_provisioning import OneTrustUserProvisioning


class Api(
    OneTrustAccessManagement,
    OneTrustAiGovernance,
    OneTrustAssessments,
    OneTrustAuditManagement,
    OneTrustBulkExport,
    OneTrustCmp,
    OneTrustComplianceAutomation,
    OneTrustConsentInterfaces,
    OneTrustConsentReceipts,
    OneTrustCookieConsent,
    OneTrustCookieConsentLegacy,
    OneTrustCookieDomainData,
    OneTrustCrossDeviceConsent,
    OneTrustDataCatalog,
    OneTrustDataDiscovery,
    OneTrustDataDiscoveryWorker,
    OneTrustDataMapping,
    OneTrustDataMappingLegacy,
    OneTrustDocuments,
    OneTrustDsar,
    OneTrustEsg,
    OneTrustIncidents,
    OneTrustIntegrations,
    OneTrustInventory,
    OneTrustIssuesManagement,
    OneTrustItRiskManagement,
    OneTrustMobileAppConsent,
    OneTrustObjectManager,
    OneTrustPolicyManagement,
    OneTrustPrivacyNotices,
    OneTrustTaskManagement,
    OneTrustTprm,
    OneTrustTraining,
    OneTrustUniversalConsent,
    OneTrustUserProvisioning,
):
    """Composite OneTrust API client — every domain client, one class."""

    __slots__ = ()
