#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustConsentInterfaces(OneTrustApiBase):
    def get_realtime_preferences(self, **kwargs) -> Response:
        """Get Data Subject's Preferences"""
        return self._call(
            http='GET',
            url_template='https://consent-api.onetrust.com/v2/preferences',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

