#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustBulkExport(OneTrustApiBase):
    def get_export_runs_get(self, **kwargs) -> Response:
        """Get List of Bulk Exports"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs',
            path_params=[],
            query_params=['page', 'size', 'sort'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def start_export_run_post(self, **kwargs) -> Response:
        """Create Bulk Export"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_credits_information_get(self, **kwargs) -> Response:
        """Get Bulk Export Credit Details"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs/credits',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_export_run_details_get(self, **kwargs) -> Response:
        """Get Bulk Export Status"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def cancel_bulk_export_delete(self, **kwargs) -> Response:
        """Cancel Bulk Export"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_attachment_download_commands_get(self, **kwargs) -> Response:
        """Get Bulk Export Download Details"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs/{id}/download',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_paginated_attachment_download_commands_get(self, **kwargs) -> Response:
        """Get List of Bulk Export Download Details"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ot-insights/v1/bulk-export-jobs/{id}/download/pages',
            path_params=['id'],
            query_params=['continuationToken', 'size'],
            has_body=False,
            paginate='cursor',
            kwargs=kwargs,
        )

