#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustAiGovernance(OneTrustApiBase):
    def assign_stage_by_name(self, **kwargs) -> Response:
        """Update Entity Workflow Stage"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/assignments/entities/{entityId}/types/{type}/stage',
            path_params=['entityId', 'type'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def add_entity_using_entity_type_id_or_entity_type_name_using_post(self, **kwargs) -> Response:
        """Create Entity"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entities',
            path_params=[],
            query_params=['entityTypeId', 'entityTypeName'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def find_all_by_type_id_and_criteria_using_post(self, **kwargs) -> Response:
        """Get Full Entity Details"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entities/search',
            path_params=[],
            query_params=['page', 'size', 'sort', 'entityTypeName'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_entity_information_using_entity_type_id_or_entity_type_name_using_get(self, **kwargs) -> Response:
        """Get Entity"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entities/{entityId}',
            path_params=['entityId'],
            query_params=['entityTypeId', 'entityTypeName'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_using_entity_type_id_or_entity_type_name_using_delete(self, **kwargs) -> Response:
        """Delete Entity"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entities/{entityId}',
            path_params=['entityId'],
            query_params=['entityTypeId', 'entityTypeName'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_using_entity_type_id_or_entity_type_name_using_patch(self, **kwargs) -> Response:
        """Modify Entity"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entities/{entityId}',
            path_params=['entityId'],
            query_params=['entityTypeId', 'entityTypeName'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def find_entity_basic_details_by_type_and_criteria_using_post(self, **kwargs) -> Response:
        """Get Basic Entity Details"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entity-basic-details/search',
            path_params=[],
            query_params=['page', 'size', 'sort'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def find_all_by_type_and_criteria_using_post_1(self, **kwargs) -> Response:
        """Get List of Entity Types"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entity-types/search',
            path_params=[],
            query_params=['page', 'size', 'sort'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_entity_type_information_using_get_1(self, **kwargs) -> Response:
        """Get Entity Type"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/entity-types/{entityTypeId}',
            path_params=['entityTypeId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_related_entities_for_an_entity_using_post(self, **kwargs) -> Response:
        """Get List of Relationship Records by Entity"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/linked-entity-types/entity-types/names/{entityTypeName}/entities/{entityId}/links/pages',
            path_params=['entityTypeName', 'entityId'],
            query_params=['page', 'size', 'sort'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_link_record_between_entities_using_link_type_id_using_post(self, **kwargs) -> Response:
        """Create Relationship Record between Entities"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/links',
            path_params=[],
            query_params=['linkTypeId'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_link_record_information_using_link_type_id_using_get(self, **kwargs) -> Response:
        """Get Relationship Record"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/links/{linkId}',
            path_params=['linkId'],
            query_params=['linkTypeId'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_link_record_by_id_and_type_using_link_type_id_using_delete(self, **kwargs) -> Response:
        """Remove Relationship Record"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/links/{linkId}',
            path_params=['linkId'],
            query_params=['linkTypeId'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def add_options_using_post(self, **kwargs) -> Response:
        """Add Options to Attribute"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/schema-attribute-options',
            path_params=[],
            query_params=['attributeId'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def add_attribute_using_post(self, **kwargs) -> Response:
        """Add Attribute to Schema"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/schema-attributes',
            path_params=[],
            query_params=['schemaName'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def disable_attribute_using_put(self, **kwargs) -> Response:
        """Disable Attribute"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/schema-attributes/{attributeId}/disable',
            path_params=['attributeId'],
            query_params=['schemaId'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def enable_attribute_using_put(self, **kwargs) -> Response:
        """Enable Attribute"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/schema-attributes/{attributeId}/enable',
            path_params=['attributeId'],
            query_params=['schemaId'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_task_using_post_1(self, **kwargs) -> Response:
        """Create Task"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/tasks',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def find_task_using_get_1(self, **kwargs) -> Response:
        """Get Task"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/tasks/{taskId}',
            path_params=['taskId'],
            query_params=['includePermissionsMetadata', 'excludeInactiveTasks'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_task_using_put_1(self, **kwargs) -> Response:
        """Update Task"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/ai-governance/v1/tasks/{taskId}',
            path_params=['taskId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

