#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustItRiskManagement(OneTrustApiBase):
    def find_all_control_implementations_attributes_and_options_by_using_post(
        self, **kwargs
    ) -> Response:
        """Search Control Implementation Attributes"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/control-implementation-attributes/search",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_all_control_implementations_using_post(self, **kwargs) -> Response:
        """Get List of Control Implementations"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/control-implementations/pages",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_control_implementation_details_using_get(self, **kwargs) -> Response:
        """Get Control Implementation"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/controls/v1/control-implementations/{guid}",
            path_params=["guid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_control_implementation_by_implementation_id_using_put(
        self, **kwargs
    ) -> Response:
        """Update Control Implementation"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/controls/v1/control-implementations/{guid}",
            path_params=["guid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_control_implementation_by_entity_and_implementation_id_using_delete(
        self, **kwargs
    ) -> Response:
        """Delete Control Implementation"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/controls/v1/control-implementations/{guid}",
            path_params=["guid"],
            query_params=["entityId"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def add_attachments_to_implementation_using_post(self, **kwargs) -> Response:
        """Attach Files to Control Implementation"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/control-implementations/{guid}/attachments",
            path_params=["guid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_control_using_post(self, **kwargs) -> Response:
        """Create Control"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/controls",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_controls_by_criteria_using_post_1(self, **kwargs) -> Response:
        """Get List of Controls"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/controls/pages",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_control_using_put_1(self, **kwargs) -> Response:
        """Update Control"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/controls/v1/controls/{controlId}",
            path_params=["controlId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_control_using_delete_1(self, **kwargs) -> Response:
        """Delete Control"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/controls/v1/controls/{controlId}",
            path_params=["controlId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def find_associated_control_implementations_using_post(self, **kwargs) -> Response:
        """Get List of Control Implementations by Entity"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/entities/{entityId}/control-implementations/pages",
            path_params=["entityId"],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_all_evidences_by_search_criteria_1(self, **kwargs) -> Response:
        """Get List of Evidence Task Implementations"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/evidence-task-implementations/pages",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_evidence_implementations_by_id_1(self, **kwargs) -> Response:
        """Get Evidence Task Implementation"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/controls/v1/evidence-task-implementations/{evidenceTaskImplementationId}",
            path_params=["evidenceTaskImplementationId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def add_evidence_implementation_attachment(self, **kwargs) -> Response:
        """Add Attachments to Evidence Task Implementation"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/evidence-task-implementations/{evidenceTaskImplementationId}/attachments",
            path_params=["evidenceTaskImplementationId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def bulk_create_links_using_post(self, **kwargs) -> Response:
        """Link Controls"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/links/bulk",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_threat_using_post_1(self, **kwargs) -> Response:
        """Create Threat"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/threats",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_threats_by_criteria_using_post(self, **kwargs) -> Response:
        """Get List of Threats"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/threats/pages",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_threat_using_delete(self, **kwargs) -> Response:
        """Delete Threat"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/controls/v1/threats/{threatId}",
            path_params=["threatId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def add_vulnerability_using_post_1(self, **kwargs) -> Response:
        """Create Vulnerability"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/vulnerabilities",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_vulnerabilities_by_criteria_using_post(self, **kwargs) -> Response:
        """Get List of Vulnerabilities"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v1/vulnerabilities/pages",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_vulnerability_using_delete(self, **kwargs) -> Response:
        """Delete Vulnerability"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/controls/v1/vulnerabilities/{vulnerabilityId}",
            path_params=["vulnerabilityId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_all_enabled_control_entity_types_using_get(self, **kwargs) -> Response:
        """Get List of Control Entity Source Types"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/controls/v2/control-entity-types",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_all_related_control_entity_types_using_get(self, **kwargs) -> Response:
        """Get Related Control Entity Types"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/controls/v2/related/control-entity-types",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_threats_using_put(self, **kwargs) -> Response:
        """Update Threats"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/controls/v2/threats",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_threats_using_post(self, **kwargs) -> Response:
        """Create Multiple Threats"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v2/threats",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_vulnerabilities_using_put(self, **kwargs) -> Response:
        """Update Vulnerabilities"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/controls/v2/vulnerabilities",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_vulnerabilities_using_post(self, **kwargs) -> Response:
        """Create Multiple Vulnerabilities"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/controls/v2/vulnerabilities",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_risk_template_using_get(self, **kwargs) -> Response:
        """Get Risk Template"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk-template/v1/templates/{riskTemplateId}",
            path_params=["riskTemplateId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def unlink_risks_from_entity_using_post(self, **kwargs) -> Response:
        """Unlink Risks"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/entities/risks/unlink",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_active_categories_using_get(self, **kwargs) -> Response:
        """Get List of Risk Categories"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk/v2/risk-categories",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_matrix_score_setting_using_get(self, **kwargs) -> Response:
        """Get Risk Matrix Configuration"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk/v2/risk-settings/matrix",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_standard_score_setting_using_get(self, **kwargs) -> Response:
        """Get Standard Risk Configuration"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk/v2/risk-settings/standard",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_risk_using_post(self, **kwargs) -> Response:
        """Create Risk"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_risk_page_view_using_post(self, **kwargs) -> Response:
        """Get List of Risks"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/pages",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_all_enabled_risk_entity_types_using_get(self, **kwargs) -> Response:
        """Get List of Risk Entity Types"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/risk-entity-types",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_all_enabled_source_entity_types_using_get(self, **kwargs) -> Response:
        """Get List of Risk Entity Source Types"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/source-entity-types",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_update_risk_using_put(self, **kwargs) -> Response:
        """Create or Update Risk"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/upsert",
            path_params=[],
            query_params=["matchAttributes"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def change_risk_stage_using_post(self, **kwargs) -> Response:
        """Update Risk Stage"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{id}/assign-stage",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_linked_risks_information_using_post(self, **kwargs) -> Response:
        """Get List of Linked Risks"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskEntityType}/{entityId}/risks",
            path_params=["riskEntityType", "entityId"],
            query_params=["page", "size", "sort", "Pageable information"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_risk_using_get(self, **kwargs) -> Response:
        """Get Risk"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}",
            path_params=["riskId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_risk_using_put(self, **kwargs) -> Response:
        """Update Risk"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_risk_using_delete(self, **kwargs) -> Response:
        """Delete Risk"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}",
            path_params=["riskId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_risk_using_patch(self, **kwargs) -> Response:
        """Modify Risk"""
        return self._call(
            http="PATCH",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def perform_risk_action_using_put(self, **kwargs) -> Response:
        """Perform Risk Action"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/actions/{action}",
            path_params=["riskId", "action"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def approve_risk_using_put(self, **kwargs) -> Response:
        """Approve Risk"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/approve",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_risk_approvers_using_put(self, **kwargs) -> Response:
        """Update Risk Approvers"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/approvers",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_risk_categories_using_put(self, **kwargs) -> Response:
        """Update Risk Categories"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/categories",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_controls_to_risk_using_post(self, **kwargs) -> Response:
        """Add Controls to Risk"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/control-implementations",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def grant_risk_exception_using_put(self, **kwargs) -> Response:
        """Grant Risk Exception"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/grant-exception",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_risk_owners_using_put(self, **kwargs) -> Response:
        """Update Risk Owners"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/owners",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def reopen_risk_using_put(self, **kwargs) -> Response:
        """Reopen Risk"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/reopen",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def request_risk_exception_using_put(self, **kwargs) -> Response:
        """Request Risk Exception"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/request-exception",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def send_back_risk_using_put(self, **kwargs) -> Response:
        """Send Back Risk"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/send-back",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def submit_risk_using_put(self, **kwargs) -> Response:
        """Submit Risk"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/submit",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_threat_to_risk(self, **kwargs) -> Response:
        """Add Threat to Risk"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/threats",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_vulnerabilities_to_risk(self, **kwargs) -> Response:
        """Add Vulnerabilities to Risk"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v2/risks/{riskId}/vulnerabilities",
            path_params=["riskId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def create_stand_alone_risk_using_post(self, **kwargs) -> Response:
        """Create Risk"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/risk/v3/risks",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )
