#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustCookieDomainData(OneTrustApiBase):
    def domaindata(self, **kwargs) -> Response:
        """Get Domain Data"""
        return self._call(
            http='GET',
            url_template='https://cookies-data.onetrust.io/bannersdk/domaindata',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

