#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustAuditManagement(OneTrustApiBase):
    def delete_scope_using_delete(self, **kwargs) -> Response:
        """Delete Audit Scope"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audit-scopes/{scopeId}',
            path_params=['scopeId'],
            query_params=['deleteFinding'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_audit_workpaper_list_view_using_post(self, **kwargs) -> Response:
        """Get List of Workpapers"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audit-workpapers/pages',
            path_params=[],
            query_params=['page', 'size', 'sort'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def edit_workpaper_details_using_post(self, **kwargs) -> Response:
        """Update Workpaper"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audit-workpapers/{workpaperId}',
            path_params=['workpaperId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_workpaper_result_using_get(self, **kwargs) -> Response:
        """Get Workpaper Results"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audit-workpapers/{workpaperId}/attribute-details',
            path_params=['workpaperId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_workpaper_basic_detail_information_using_get(self, **kwargs) -> Response:
        """Get Workpaper Control Details"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audit-workpapers/{workpaperId}/control-details',
            path_params=['workpaperId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def validate_and_create_audit_using_post(self, **kwargs) -> Response:
        """Create Audit"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audits',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_audit_list_page_using_post(self, **kwargs) -> Response:
        """Get List of Audits"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audits/pages',
            path_params=[],
            query_params=['page', 'size', 'sort'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_audit_detail_using_get(self, **kwargs) -> Response:
        """Get Audit"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audits/{auditId}',
            path_params=['auditId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def validate_and_update_audit_using_put(self, **kwargs) -> Response:
        """Update Audit"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audits/{auditId}',
            path_params=['auditId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_audit_using_delete(self, **kwargs) -> Response:
        """Delete Audit"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audits/{auditId}',
            path_params=['auditId'],
            query_params=['deleteFinding'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def validate_and_reassign_scopes_using_put(self, **kwargs) -> Response:
        """Update Audit Scope"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/audit-management/v1/audits/{auditId}/reassign-scopes',
            path_params=['auditId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

