#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustMobileAppConsent(OneTrustApiBase):
    def applicationdata(self, **kwargs) -> Response:
        """Get SDK Configuration"""
        return self._call(
            http="GET",
            url_template="https://customer.my.onetrust.com/bannersdk/v2/applicationdata",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
