#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustDocuments(OneTrustApiBase):
    def file_upload(self, **kwargs) -> Response:
        """Upload File"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/document/v2/attachments',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def file_location(self, **kwargs) -> Response:
        """Get File Location"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/document/v3/attachments/{attachmentId}/content',
            path_params=['attachmentId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

