#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustCrossDeviceConsent(OneTrustApiBase):
    def get_preferences_using_get(self, **kwargs) -> Response:
        """Get Data Subject's Preferences"""
        return self._call(
            http="GET",
            url_template="https://consent-api.onetrust.com/v1/preferences",
            path_params=[],
            query_params=["syncGroup"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
