#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustDataCatalog(OneTrustApiBase):
    def get_all_glossaries_names(self, **kwargs) -> Response:
        """Get List of Glossaries"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/glossaries/all/names',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_all_glossaries_by_names(self, **kwargs) -> Response:
        """Get Glossary"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/glossaries/name/{glossaryName}',
            path_params=['glossaryName'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def retrieve_all_tags_name(self, **kwargs) -> Response:
        """Get List of Tags"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/tag-names',
            path_params=[],
            query_params=['type'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_tag_details_with_associated_terms(self, **kwargs) -> Response:
        """Get Tag"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/tags/{name}/details',
            path_params=['name'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def retrieve_all_terms(self, **kwargs) -> Response:
        """Get List of Terms"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/terms',
            path_params=[],
            query_params=['name', 'page', 'size'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def get_term_attribute_by_name(self, **kwargs) -> Response:
        """Get Term Attribute"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/terms/attribute-details/{name}',
            path_params=['name'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_all_term_attribute_names(self, **kwargs) -> Response:
        """Get List of Term Attributes"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/terms/attribute-names',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def retrieve_terms_by_name(self, **kwargs) -> Response:
        """Get Term"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/terms/name/{termName}',
            path_params=['termName'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def retrieve_terms_name(self, **kwargs) -> Response:
        """Get List of Term Names"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/glossary/v1/terms/names',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_tag_v2(self, **kwargs) -> Response:
        """Create Tag"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/glossary/v2/tags',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_term_using_post(self, **kwargs) -> Response:
        """Create Term"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/glossary/v2/terms',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_or_upsert_data_asset_v1(self, **kwargs) -> Response:
        """Create Data Asset"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_data_asset_v1(self, **kwargs) -> Response:
        """Get Data Asset"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_data_asset_v1(self, **kwargs) -> Response:
        """Delete Data Asset"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_data_asset_v1(self, **kwargs) -> Response:
        """Modify Data Asset"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_data_asset_tag_associations_v1(self, **kwargs) -> Response:
        """Create Tag Associations"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}/tags',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_data_asset_tag_associations_v1(self, **kwargs) -> Response:
        """Delete Multiple Data Asset Tag Associations"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}/tags/deleteTagAssociations',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_data_asset_term_associations_v1(self, **kwargs) -> Response:
        """Create Term Associations"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}/terms',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_data_asset_term_associations_v1(self, **kwargs) -> Response:
        """Delete Multiple Data Asset Term Associations"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v1/data-assets/{dataAssetId}/terms/deleteTermAssociations',
            path_params=['dataAssetId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_data_asset_attribute_by_name(self, **kwargs) -> Response:
        """Get Data Asset Attribute"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/metadata-catalog/v1/metadata/attribute-details/{name}',
            path_params=['name'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_all_data_asset_attribute_names(self, **kwargs) -> Response:
        """Get List of Data Asset Attributes"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/metadata-catalog/v1/metadata/attribute-names',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def external_search(self, **kwargs) -> Response:
        """Get Catalog Search Results"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v1/catalog/search',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_v1_field_details(self, **kwargs) -> Response:
        """Get Search Fields"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/data-governance/v1/field-details',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def external_search_using_continuationtoken(self, **kwargs) -> Response:
        """Get Catalog Search Results"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/data-governance/v2/catalog/search',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

