#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustCookieConsent(OneTrustApiBase):
    def create_application(self, **kwargs) -> Response:
        """Create Application"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/application",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def scan_application(self, **kwargs) -> Response:
        """Scan Application"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/application/{id}/scan",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_applications(self, **kwargs) -> Response:
        """Get List of Applications"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/applications",
            path_params=[],
            query_params=["searchStr", "sortBy", "direction", "page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_application_branding_attribute_list(self, **kwargs) -> Response:
        """Get Branding Attributes for Application"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/applications/{id}/branding-attributes",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_application_branding_attributes_for_public_api(
        self, **kwargs
    ) -> Response:
        """Update Branding Attributes for Application"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/applications/{id}/branding-attributes",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def publish_app_script(self, **kwargs) -> Response:
        """Publish Application SDK"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/applications/{id}/publish",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_app_script_details(self, **kwargs) -> Response:
        """Get Script for Application"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/applications/{id}/script-details",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_categorized_cookies(self, **kwargs) -> Response:
        """Get Categorized Cookies"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/cookies/categorized",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def publish_script_to_site(self, **kwargs) -> Response:
        """Publish Script to Website"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/publish",
            path_params=[],
            query_params=["scriptType", "website"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_script_for_website(self, **kwargs) -> Response:
        """Get Script for Website"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/scripts",
            path_params=[],
            query_params=["scriptType", "website"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_domain(self, **kwargs) -> Response:
        """Delete Domain"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/{domainId}",
            path_params=["domainId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_domain_group(self, **kwargs) -> Response:
        """Create or Update Domain Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/{domainId}/domaingroup",
            path_params=["domainId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_script_details(self, **kwargs) -> Response:
        """Get Script for Domain"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/{domainId}/script-details",
            path_params=["domainId"],
            query_params=["scriptType"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def download_script_file(self, **kwargs) -> Response:
        """Download Script File"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/{domainId}/scripts",
            path_params=["domainId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_branding_attribute_list(self, **kwargs) -> Response:
        """Get Branding Attributes for Domain"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/{id}/branding-attributes",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_branding_attributes_for_public_api(self, **kwargs) -> Response:
        """Update Branding Attributes for Domain"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/domains/{id}/branding-attributes",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_geo_rule_groups(self, **kwargs) -> Response:
        """Get List of Geolocation Rule Groups"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/georulegroups",
            path_params=[],
            query_params=["searchStr", "sortBy", "direction", "page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_geo_rule_group_details(self, **kwargs) -> Response:
        """Get Geolocation Rule Group"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/georulegroups/{geoRuleGroupId}",
            path_params=["geoRuleGroupId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def assign_entities_to_geo_rule_group(self, **kwargs) -> Response:
        """Assign Geolocation Rule Group"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/georulegroups/{geoRuleGroupId}/assign",
            path_params=["geoRuleGroupId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_templates(self, **kwargs) -> Response:
        """Get List of Templates"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/templates",
            path_params=[],
            query_params=["searchStr", "sortBy", "direction", "page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_template_details(self, **kwargs) -> Response:
        """Get Template Details"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/templates/{templateId}",
            path_params=["templateId"],
            query_params=["language"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_domains_scanned_by_sort(self, **kwargs) -> Response:
        """Get List of Websites"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans",
            path_params=[],
            query_params=[
                "searchStr",
                "externalOrgId",
                "page",
                "size",
                "sortBy",
                "direction",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def add_scans(self, **kwargs) -> Response:
        """Scan Websites"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans",
            path_params=[],
            query_params=["externalOrgId"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def archive_scans(self, **kwargs) -> Response:
        """Archive Scans"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/archive",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def bulk_edit_cookies(self, **kwargs) -> Response:
        """Edit Cookies"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/cookies",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def bulk_add_cookies(self, **kwargs) -> Response:
        """Add Cookies"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/cookies",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def bulk_delete_cookies(self, **kwargs) -> Response:
        """Delete Cookies"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/cookies",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def schedule_scans(self, **kwargs) -> Response:
        """Schedule Website Scans"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/domains/schedule",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def bulk_cancel_domain_schedule(self, **kwargs) -> Response:
        """Cancel Scheduled Website Scans"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/domains/schedule/cancel",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_domain_scans(self, **kwargs) -> Response:
        """Get List of Scans by Domain"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/domains/{domainId}/scans",
            path_params=["domainId"],
            query_params=[
                "status",
                "archiveStatus",
                "startDate",
                "endDate",
                "page",
                "size",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_scan_delta_details(self, **kwargs) -> Response:
        """Get List of Added or Removed Cookies"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/domains/{domainId}/scans/{scanId}/scandelta",
            path_params=["domainId", "scanId"],
            query_params=["language", "countryCode"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_detailed_scan_result_information(self, **kwargs) -> Response:
        """Get Scan Results"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/domains/{domainId}/scans/{scanId}/scanresults",
            path_params=["domainId", "scanId"],
            query_params=["language", "countryCode", "entityType", "page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_scan_result_summary(self, **kwargs) -> Response:
        """Get Scan Result Summary"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/domains/{domainId}/scans/{scanId}/summary",
            path_params=["domainId", "scanId"],
            query_params=["language", "countryCode"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_cookies_by_filter(self, **kwargs) -> Response:
        """Get List of Cookies by Criteria"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/languages/{language}/cookies/filter",
            path_params=["language"],
            query_params=[
                "countryCode",
                "cookieName",
                "sortBy",
                "direction",
                "page",
                "size",
            ],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def check_scans_status(self, **kwargs) -> Response:
        """Get Scan Statuses"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/status",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def cancel_scan(self, **kwargs) -> Response:
        """Cancel Scan"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/{scanId}/cancel",
            path_params=["scanId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def recategorize_cookies_by_scan(self, **kwargs) -> Response:
        """Recategorize Cookies"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/cmp/v1/webscans/{scanId}/recategorize",
            path_params=["scanId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
