#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustCmp(OneTrustApiBase):
    def get_banner(self, **kwargs) -> Response:
        """Get Banner Data"""
        return self._call(
            http="GET",
            url_template="https://mobile-data.onetrust.io/cfw/cmp/v1/banner",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_preferences(self, **kwargs) -> Response:
        """Get Preference Center Data"""
        return self._call(
            http="GET",
            url_template="https://mobile-data.onetrust.io/cfw/cmp/v1/preferences",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def post_log_consent(self, **kwargs) -> Response:
        """Log Consent"""
        return self._call(
            http="POST",
            url_template="https://mobile-data.onetrust.io/cfw/cmp/v1/save-log-consent",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_ucpurposes(self, **kwargs) -> Response:
        """Get Universal Consent Purposes"""
        return self._call(
            http="GET",
            url_template="https://mobile-data.onetrust.io/cfw/cmp/v1/uc-purposes",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_vendors(self, **kwargs) -> Response:
        """Get IAB and Google Vendors"""
        return self._call(
            http="GET",
            url_template="https://mobile-data.onetrust.io/cfw/cmp/v1/vendors",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
