#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustTprm(OneTrustApiBase):
    def create_vendor_contract_using_post(self, **kwargs) -> Response:
        """Create Contract"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/add",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_contract_schema_using_get(self, **kwargs) -> Response:
        """Get Contract Schema"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/schemas",
            path_params=[],
            query_params=["activeStatus"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def fetch_all_contract_types_using_get(self, **kwargs) -> Response:
        """Get List of Contract Types"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/types",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def search_contract_by_vendor_and_criteria_using_post(self, **kwargs) -> Response:
        """Search Contracts"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/vendors/{vendorId}/contracts",
            path_params=["vendorId"],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_vendor_contract_using_delete(self, **kwargs) -> Response:
        """Delete Contract"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/{contractId}",
            path_params=["contractId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def load_vendor_contract_by_contract_id_using_get(self, **kwargs) -> Response:
        """Get Contract"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/{contractId}/contracts",
            path_params=["contractId"],
            query_params=["excludeAttachments"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_vendor_contract_using_put(self, **kwargs) -> Response:
        """Update Contract"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/vendor/v1/contracts/{contractId}/vendors/{vendorId}/contracts",
            path_params=["contractId", "vendorId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_engagement_schema_using_get(self, **kwargs) -> Response:
        """Get Engagement Schema"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagement-schemas",
            path_params=[],
            query_params=["activeStatus"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def load_engagement_by_engagement_id_using_get(self, **kwargs) -> Response:
        """Get Engagement"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagements/{engagementId}",
            path_params=["engagementId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_engagement_using_put(self, **kwargs) -> Response:
        """Update Engagement"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagements/{engagementId}",
            path_params=["engagementId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_engagement_using_delete(self, **kwargs) -> Response:
        """Delete Engagement"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagements/{engagementId}",
            path_params=["engagementId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_engagement_using_patch(self, **kwargs) -> Response:
        """Modify Engagement"""
        return self._call(
            http="PATCH",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagements/{engagementId}",
            path_params=["engagementId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_engagement_status(self, **kwargs) -> Response:
        """Update Engagement Status"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagements/{engagementId}/status",
            path_params=["engagementId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def load_engagement_using_get(self, **kwargs) -> Response:
        """Search Engagements"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/vendor/v1/engagements-search",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def create_engagement_using_post(self, **kwargs) -> Response:
        """Create Engagement"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/vendor/v1/vendor-engagements",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )
