#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustDataDiscovery(OneTrustApiBase):
    def get_credentials(self, **kwargs) -> Response:
        """Get List of Credentials"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/credentials',
            path_params=[],
            query_params=['name', 'systemName', 'page', 'size', 'sort'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def update_credential(self, **kwargs) -> Response:
        """Update Credential"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/credentials',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_credential(self, **kwargs) -> Response:
        """Create Credential"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/credentials',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_credential_by_id(self, **kwargs) -> Response:
        """Get Credential"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/credentials/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_credential(self, **kwargs) -> Response:
        """Delete Credential"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/credentials/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_job_using_post_x(self, **kwargs) -> Response:
        """Create Scan Job"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-job',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_scan_jobs_by_data_source_using_get_1(self, **kwargs) -> Response:
        """Get List of Scan Jobs"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-job/datasource/{dataSourceId}',
            path_params=['dataSourceId'],
            query_params=['status', 'scanLevel', 'isManual', 'createdFrom', 'createdTo', 'page', 'size', 'sort'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def get_job_by_id_using_get(self, **kwargs) -> Response:
        """Get Scan Job"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-job/{jobId}',
            path_params=['jobId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def cancel_job_using_patch(self, **kwargs) -> Response:
        """Cancel Scan Job"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-job/{jobId}/cancel',
            path_params=['jobId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_all_using_get_2(self, **kwargs) -> Response:
        """Get List of Scan Profiles"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-profiles',
            path_params=[],
            query_params=['search', 'systemName', 'scanType', 'createdFrom', 'createdTo', 'page', 'size', 'sort'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def update_v2_using_put(self, **kwargs) -> Response:
        """Update Scan Profile"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-profiles',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_v2_using_post(self, **kwargs) -> Response:
        """Create Scan Profile"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-profiles',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_scan_profile_using_get_1(self, **kwargs) -> Response:
        """Get Scan Profile"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-profiles/{scanProfileId}',
            path_params=['scanProfileId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_scan_profile_using_delete_1(self, **kwargs) -> Response:
        """Delete Scan Profile"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scan-profiles/{scanProfileId}',
            path_params=['scanProfileId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_job_using_get_1(self, **kwargs) -> Response:
        """Get Scan Job"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scanners/{scannerId}/jobs/{jobId}',
            path_params=['scannerId', 'jobId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def cancel_scan_job(self, **kwargs) -> Response:
        """Cancel Scan Job"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v2/scanners/{scannerId}/jobs/{jobId}/cancel',
            path_params=['scannerId', 'jobId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_docker_repository_tags_using_get(self, **kwargs) -> Response:
        """Get List of Image tags"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v3/docker-repository-tags',
            path_params=[],
            query_params=['version'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_all_using_get_1(self, **kwargs) -> Response:
        """Get List of Data Sources"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v3/system',
            path_params=[],
            query_params=['page', 'size', 'sort', 'name', 'systemType', 'createdFrom', 'createdTo', 'oneTrustAssetId', 'status', 'workerNodeId'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def upsert_source_system_v3_using_put(self, **kwargs) -> Response:
        """Create or Update Data Source"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v3/system',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_data_source_by_id_using_get_1(self, **kwargs) -> Response:
        """Get Data Source"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v3/system/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_system_using_delete_1(self, **kwargs) -> Response:
        """Delete Data Source"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/discovery-scan-config/v3/system/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def list_detectors(self, **kwargs) -> Response:
        """Get List of Custom Classifiers"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/label-manager/v2/custom-classifiers',
            path_params=[],
            query_params=['searchTerm', 'mappedTermId'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_detector(self, **kwargs) -> Response:
        """Create Custom Classifier"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/label-manager/v2/custom-classifiers',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_detector_by_classifier_name(self, **kwargs) -> Response:
        """Get Custom Classifier"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/label-manager/v2/custom-classifiers/{classifierName}',
            path_params=['classifierName'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_detector(self, **kwargs) -> Response:
        """Update Custom Classifier"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/label-manager/v2/custom-classifiers/{classifierName}',
            path_params=['classifierName'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_detector(self, **kwargs) -> Response:
        """Delete Custom Classifier"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/label-manager/v2/custom-classifiers/{classifierName}',
            path_params=['classifierName'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

