#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustUserProvisioning(OneTrustApiBase):
    def list_groups_using_get(self, **kwargs) -> Response:
        """Get List of Groups"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v2/Groups',
            path_params=[],
            query_params=['startIndex', 'count'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_group_resource_using_get(self, **kwargs) -> Response:
        """Get Group"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v2/Groups/{groupId}',
            path_params=['groupId'],
            query_params=['excludedAttributes'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_group_members_using_put(self, **kwargs) -> Response:
        """Update Group"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/scim/v2/Groups/{groupId}',
            path_params=['groupId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def update_group_members_using_patch(self, **kwargs) -> Response:
        """Modify Group"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/scim/v2/Groups/{groupId}',
            path_params=['groupId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_all_users_using_get(self, **kwargs) -> Response:
        """Get List of Users"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v2/Users',
            path_params=[],
            query_params=['startIndex', 'count'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_user_using_post(self, **kwargs) -> Response:
        """Create User"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/scim/v2/Users',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_user_using_get(self, **kwargs) -> Response:
        """Get User"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v2/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_user_using_put(self, **kwargs) -> Response:
        """Update User"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/scim/v2/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_user_using_delete(self, **kwargs) -> Response:
        """Delete User"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/scim/v2/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def patch_user_using_patch(self, **kwargs) -> Response:
        """Modify User"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/scim/v2/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_groups(self, **kwargs) -> Response:
        """Get List of User Groups"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/Groups',
            path_params=[],
            query_params=['startIndex', 'count', 'excludedAttributes', 'filter'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_group(self, **kwargs) -> Response:
        """Create User Group"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/scim/v3/Groups',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_group_by_id(self, **kwargs) -> Response:
        """Get User Group"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/Groups/{groupId}',
            path_params=['groupId'],
            query_params=['excludedAttributes'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_group(self, **kwargs) -> Response:
        """Update User Group"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/scim/v3/Groups/{groupId}',
            path_params=['groupId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def delete_group(self, **kwargs) -> Response:
        """Delete User Group"""
        return self._call(
            http='DELETE',
            url_template='https://__HOSTNAME__/api/scim/v3/Groups/{groupId}',
            path_params=['groupId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def modify_group(self, **kwargs) -> Response:
        """Modify User Group"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/scim/v3/Groups/{groupId}',
            path_params=['groupId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_resource_types_using_get(self, **kwargs) -> Response:
        """Get Supported Resources"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/ResourceTypes',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_resource_types_by_name_using_get(self, **kwargs) -> Response:
        """Get Supported Resource Types"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/ResourceTypes/{resourceName}',
            path_params=['resourceName'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_schemas_using_get(self, **kwargs) -> Response:
        """Get List of Supported SCIM Schemas"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/Schemas',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_schemas_by_name_using_get(self, **kwargs) -> Response:
        """Get SCIM Schema"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/Schemas/{schemaName}',
            path_params=['schemaName'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_service_provider_config_using_get(self, **kwargs) -> Response:
        """Get Service Provider Configuration"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/ServiceProviderConfig',
            path_params=[],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def get_users(self, **kwargs) -> Response:
        """Get List of Users"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/Users',
            path_params=[],
            query_params=['startIndex', 'count', 'filter'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def create_user(self, **kwargs) -> Response:
        """Create User"""
        return self._call(
            http='POST',
            url_template='https://__HOSTNAME__/api/scim/v3/Users',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_user_by_id(self, **kwargs) -> Response:
        """Get User"""
        return self._call(
            http='GET',
            url_template='https://__HOSTNAME__/api/scim/v3/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def update_user(self, **kwargs) -> Response:
        """Update User"""
        return self._call(
            http='PUT',
            url_template='https://__HOSTNAME__/api/scim/v3/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def modify_user(self, **kwargs) -> Response:
        """Modify User"""
        return self._call(
            http='PATCH',
            url_template='https://__HOSTNAME__/api/scim/v3/Users/{id}',
            path_params=['id'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

