#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustUniversalConsent(OneTrustApiBase):
    def get_collection_points_using_get(self, **kwargs) -> Response:
        """Get List of Collection Points"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/collectionpoints",
            path_params=[],
            query_params=[
                "dataElementGuid",
                "organizationId",
                "page",
                "size",
                "sort",
                "name",
                "purposeGuid",
                "collectionPointType",
                "consentType",
                "status",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def create_collection_point_using_post(self, **kwargs) -> Response:
        """Create Collection Point"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/collectionpoints",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_token_using_get(self, **kwargs) -> Response:
        """Get Collection Point Token"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/collectionpoints/{collectionpointGuid}/token",
            path_params=["collectionpointGuid"],
            query_params=["version", "state"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def edit_collection_point_using_put(self, **kwargs) -> Response:
        """Update Existing Collection Point"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/collectionpoints/{collectionpointId}",
            path_params=["collectionpointId"],
            query_params=["version"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def disable_collection_point_using_put(self, **kwargs) -> Response:
        """Update Collection Point Status"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/collectionpoints/{collectionpointId}/disable",
            path_params=["collectionpointId"],
            query_params=["value"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_index(self, **kwargs) -> Response:
        """Create Custom Index"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/custom-indexes",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_index_creation_status(self, **kwargs) -> Response:
        """Get Index Creation Status"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/custom-indexes/{runId}/status",
            path_params=["runId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_list_using_get(self, **kwargs) -> Response:
        """Get List of Purpose Preferences"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/custompreferences",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def create_custom_preference_using_post(self, **kwargs) -> Response:
        """Create Purpose Preference"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/custompreferences",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def edit_custom_preference_using_put(self, **kwargs) -> Response:
        """Update Purpose Preference"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/custompreferences/{customPreferenceId}",
            path_params=["customPreferenceId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def find_by_guid_using_get(self, **kwargs) -> Response:
        """Get Purpose Preference"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/custompreferences/{custompreferenceId}",
            path_params=["custompreferenceId"],
            query_params=["includeTranslations"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_or_update_data_subject_using_post(self, **kwargs) -> Response:
        """Update Data Subject's Data Elements"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/datasubjects/dataelements",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def merge_data_subjects_using_post(self, **kwargs) -> Response:
        """Deduplicate Data Subjects"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/datasubjects/merge",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def merge_datasubject_using_post(self, **kwargs) -> Response:
        """Deduplicate Data Subjects"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/datasubjects/merge/{mergeRequestId}",
            path_params=["mergeRequestId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subject_profile_using_get(self, **kwargs) -> Response:
        """Get List of Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/datasubjects/profiles",
            path_params=[],
            query_params=[
                "since",
                "toDate",
                "updatedSince",
                "identifier",
                "purposeGuid",
                "collectionPointGuid",
                "collectionPointName",
                "properties",
                "includeEffectiveStatus",
                "linkedIdentityGroupId",
                "includeConsentAttachments",
                "isDNCInclude",
                "includeDSWithNoOrg",
                "includeGeolocation",
                "page",
                "size",
                "sort",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_data_subject_purposes_by_identifier_using_get(self, **kwargs) -> Response:
        """Get List of Purposes for a Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/datasubjects/purposes",
            path_params=[],
            query_params=["identifier", "page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def exportduplicatedatasubject(self, **kwargs) -> Response:
        """Generate Export of Duplicate Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/export-duplicate-datasubject/{mergeRequestId}",
            path_params=["mergeRequestId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_link_tokens_using_get(self, **kwargs) -> Response:
        """Get List of Data Subject Tokens"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/linktokens",
            path_params=[],
            query_params=["since", "until", "page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_data_subject_purposes_by_identifier_using_get_1(self, **kwargs) -> Response:
        """Get Data Subject's Preferences in a Preference Center"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/preferencecenters/{prefcenterId}/datasubjects/preferences",
            path_params=["prefcenterId"],
            query_params=["identifier"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_preferences_for_data_subject_api_using_put(self, **kwargs) -> Response:
        """Update Data Subject's Preferences in a Preference Center"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/preferencecenters/{prefcenterId}/datasubjects/preferences",
            path_params=["prefcenterId"],
            query_params=["identifier"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def withdraw_preferences_api_using_delete(self, **kwargs) -> Response:
        """Withdraw Data Subject's Consent for All Purposes in a Preference Center"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/preferencecenters/{prefcenterId}/datasubjects/preferences",
            path_params=["prefcenterId"],
            query_params=["identifier"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_preference_center_by_id_using_get(self, **kwargs) -> Response:
        """Get Preference Center Schema"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/preferencecenters/{prefcenterId}/preferences",
            path_params=["prefcenterId"],
            query_params=["state"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_purposes_using_get(self, **kwargs) -> Response:
        """Get List of Purposes"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def create_purpose_using_post(self, **kwargs) -> Response:
        """Create Purpose"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes",
            path_params=[],
            query_params=["isInternalOrg"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def create_new_purpose_version_using_post(self, **kwargs) -> Response:
        """Create New Purpose Version"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes/{purposeGuid}",
            path_params=["purposeGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def edit_purpose_using_put(self, **kwargs) -> Response:
        """Update Purpose"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes/{purposeId}",
            path_params=["purposeId"],
            query_params=["isInternalOrg"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subjects_for_purposes_using_get(self, **kwargs) -> Response:
        """Get List of Data Subjects by Purpose"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes/{purposeId}/datasubjects",
            path_params=["purposeId"],
            query_params=[
                "lastTransactionDate",
                "transactionStatus",
                "includeCustomPreferences",
            ],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def publish_purpose_using_put(self, **kwargs) -> Response:
        """Publish Purpose"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes/{purposeId}/publish",
            path_params=["purposeId"],
            query_params=["version"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def set_retirement_using_put(self, **kwargs) -> Response:
        """Retire Purpose"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/purposes/{purposeId}/retire",
            path_params=["purposeId"],
            query_params=["date"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_receipt_list_using_get(self, **kwargs) -> Response:
        """Get List of Receipts by Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/receipt-list",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_receipt_list_details_using_get(self, **kwargs) -> Response:
        """Get List of Receipt Details by Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/receipts",
            path_params=[],
            query_params=["includeNotgiven", "page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def find_receipt_using_get(self, **kwargs) -> Response:
        """Get Receipt"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/receipts/{id}",
            path_params=["id"],
            query_params=["includeNotgiven", "includeConsentStrings"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_paged_merge_request_using_get(self, **kwargs) -> Response:
        """Get List of Scheduled Exports"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/scheduled-jobs/merge-request",
            path_params=[],
            query_params=["page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def schedule_merge_request_using_post(self, **kwargs) -> Response:
        """Create Scheduled Export of Duplicate Data Subjects"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/scheduled-jobs/merge-request",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_merge_request_using_get(self, **kwargs) -> Response:
        """Get Scheduled Export"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/scheduled-jobs/merge-request/{mergeRequestGuid}",
            path_params=["mergeRequestGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_merge_request_using_delete(self, **kwargs) -> Response:
        """Delete Scheduled Export"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/scheduled-jobs/merge-request/{mergeRequestGuid}",
            path_params=["mergeRequestGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def withdraw_transaction_behalf_of_datasubject_using_put(
        self, **kwargs
    ) -> Response:
        """Withdraw Consent on Behalf of a Data Subject"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/transactions/withdraw/fordatasubject",
            path_params=[],
            query_params=["identifier", "withdrawnBy"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def withdraw_transaction_by_purpose_and_identifier_using_get(
        self, **kwargs
    ) -> Response:
        """Withdraw Data Subject's Consent"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v1/transactions/withdraw/purpose/{purposeId}",
            path_params=["purposeId"],
            query_params=["identifier"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_collection_points_using_get_1(self, **kwargs) -> Response:
        """Get List of Collection Points"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/collectionpoints",
            path_params=[],
            query_params=[
                "organizationId",
                "id",
                "version",
                "status",
                "page",
                "size",
                "sort",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def create_version_using_post(self, **kwargs) -> Response:
        """Create New Collection Point Version"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/collectionpoints/{collectionPointGuid}/version",
            path_params=["collectionPointGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subjects_using_get(self, **kwargs) -> Response:
        """Get List of Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/datasubjects",
            path_params=[],
            query_params=[
                "page",
                "size",
                "updatedSince",
                "updatedUntil",
                "id",
                "language",
                "properties",
                "includeDataSubjectsWithOutPurposeTransactions",
                "isDNCInclude",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def delete_data_subject_profiles_using_delete(self, **kwargs) -> Response:
        """Delete Purposes from Data Subject"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/datasubjects/profiles",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def search_data_subjects_post_using_post(self, **kwargs) -> Response:
        """Search Data Subjects"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/datasubjects/search",
            path_params=[],
            query_params=["page", "size", "isDNCInclude"],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_linked_identity_groups_using_get(self, **kwargs) -> Response:
        """Get List of Data Subject Groups"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/linkedidentitygroups",
            path_params=[],
            query_params=["displayOrganizations", "page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def create_linked_identity_group_using_post(self, **kwargs) -> Response:
        """Create Data Subject Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/linkedidentitygroups",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_linked_identity_group_using_get(self, **kwargs) -> Response:
        """Get Data Subject Group"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/linkedidentitygroups/{linkedIdentityGroupId}",
            path_params=["linkedIdentityGroupId"],
            query_params=["displayOrganizations"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_linked_identity_group_using_put(self, **kwargs) -> Response:
        """Update Data Subject Group"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/linkedidentitygroups/{linkedIdentityGroupId}",
            path_params=["linkedIdentityGroupId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_using_delete(self, **kwargs) -> Response:
        """Delete Data Subject Group"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/linkedidentitygroups/{linkedIdentityGroupId}",
            path_params=["linkedIdentityGroupId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_preference_center_page_schema_using_get(self, **kwargs) -> Response:
        """Get Preference Center Page Schema"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/preferencecenterpage/{preferencecenterpageid}/schema",
            path_params=["preferencecenterpageid"],
            query_params=["state"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_preference_centers_using_get(self, **kwargs) -> Response:
        """Get List of Preference Centers"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/preferencecenters",
            path_params=[],
            query_params=["page", "size", "sort", "dataElementGuid"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_root_schema_using_get(self, **kwargs) -> Response:
        """Get Preference Center Root Schema"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/preferencecenters/{preferencecenterid}/schema",
            path_params=["preferencecenterid"],
            query_params=["state"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_grouped_purposes_v2(self, **kwargs) -> Response:
        """Get List of Purpose Versions"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/purposes",
            path_params=[],
            query_params=[
                "latestVersion",
                "includeRetired",
                "organization",
                "includeCustomPreferences",
                "includeTopics",
                "fromLastModifiedDate",
                "toLastModifiedDate",
                "page",
                "size",
                "sort",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_purpose_detail_using_get(self, **kwargs) -> Response:
        """Get Purpose"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consentmanager/v2/purposes/{purposeId}",
            path_params=["purposeId"],
            query_params=["status", "version"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_consent_group_list_using_get(self, **kwargs) -> Response:
        """Get List of Consent Groups"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups",
            path_params=[],
            query_params=["name"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_consent_group_using_post(self, **kwargs) -> Response:
        """Create Consent Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_consent_group_settings_using_get(self, **kwargs) -> Response:
        """Get Priority Scores for Purpose Statuses"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/settings",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_consent_group_settings_using_put(self, **kwargs) -> Response:
        """Update Priority Scores for Purpose Statuses"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/settings",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_consent_group_using_get(self, **kwargs) -> Response:
        """Get Consent Group"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}",
            path_params=["consentGroupGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def add_consent_groups_to_consent_group_using_post(self, **kwargs) -> Response:
        """Add Consent Groups to Parent Consent Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/consent-groups",
            path_params=["consentGroupGuid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def unlink_consent_group_using_delete(self, **kwargs) -> Response:
        """Remove Consent Groups from Parent Consent Group"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/consent-groups",
            path_params=["consentGroupGuid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_data_subjects_to_consent_group_using_post(self, **kwargs) -> Response:
        """Add Data Subjects to Parent Consent Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/data-subjects",
            path_params=["consentGroupGuid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_data_subjects_to_consent_group_using_delete(self, **kwargs) -> Response:
        """Remove Data Subject from Parent Consent Group"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/data-subjects/{dataSubjectGuid}",
            path_params=["consentGroupGuid", "dataSubjectGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def update_purpose_rules_to_consent_group_using_put(self, **kwargs) -> Response:
        """Update Consent Group Purpose Rule"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/purpose-rules",
            path_params=["consentGroupGuid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def add_purpose_rules_to_consent_group_using_post(self, **kwargs) -> Response:
        """Add Purpose Rules to Consent Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/purpose-rules",
            path_params=["consentGroupGuid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_consent_group_purpose_rule_using_delete(self, **kwargs) -> Response:
        """Remove Purpose Rule from Consent Group"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consent/v2/consent-groups/{consentGroupGuid}/purpose-rules/{purposeGuid}",
            path_params=["consentGroupGuid", "purposeGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_purpose_from_data_subject_using_delete(self, **kwargs) -> Response:
        """Delete Purpose from Data Subjects"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consent/v2/datasubject-purposes/{purposeGuid}",
            path_params=["purposeGuid"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_data_subject_profile_using_delete(self, **kwargs) -> Response:
        """Delete Data Subjects"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/api/consent/v2/datasubjects",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_receipt_list_details_using_post(self, **kwargs) -> Response:
        """Get List of Receipts"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consent/v2/receipts",
            path_params=[],
            query_params=[
                "collectionPointGuid",
                "receiptId",
                "purposeGuid",
                "organizationId",
                "fromDate",
                "toDate",
                "includeDataElements",
                "includeArchived",
                "isAnonymous",
                "includeConsentStrings",
                "page",
                "size",
                "sort",
            ],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_transactions_using_post(self, **kwargs) -> Response:
        """Get List of Transactions"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/api/consent/v2/transactions",
            path_params=[],
            query_params=[
                "fromDate",
                "toDate",
                "collectionPointGuid",
                "page",
                "size",
                "sort",
            ],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_list_of_deletion_certificates(self, **kwargs) -> Response:
        """Get List of Deletion Certificates"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v1/deletion-certificates",
            path_params=[],
            query_params=["page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def cross_device_consent_using_delete(self, **kwargs) -> Response:
        """Delete Cross Device Consents and Receipts"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/rest/api/consent/v1/receipts/cross-device",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_data_subject_using_ttl(self, **kwargs) -> Response:
        """Delete Data Subject"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/data-subjects",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def delete_purpose_from_data_subjects_using_ttl(self, **kwargs) -> Response:
        """Delete Purposes from Data Subjects"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/data-subjects/profiles",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subjects_v4(self, **kwargs) -> Response:
        """Get List of Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects",
            path_params=[],
            query_params=["fromDate", "toDate", "isDNCInclude", "page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_data_subject_basic_details_v4(self, **kwargs) -> Response:
        """Get Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/basic-details",
            path_params=[],
            query_params=["isDNCInclude"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subject_details_v4(self, **kwargs) -> Response:
        """Get Data Subject Details"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/details",
            path_params=[],
            query_params=[
                "includeConsentGroups",
                "includeAttachments",
                "includeNotices",
                "includeConsentStrings",
                "isDNCInclude",
            ],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_all_profiles_by_data_subject_v4(self, **kwargs) -> Response:
        """Get List of All Purpose Details by Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/ds-profiles",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_email_link_token_by_data_subject_v4(self, **kwargs) -> Response:
        """Get Data Subject Token"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/linktokens",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subject_profiles_v4(self, **kwargs) -> Response:
        """Get List of All Purpose Details for All Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/profiles",
            path_params=[],
            query_params=[
                "collectionPointId",
                "purposeId",
                "status",
                "updatedSince",
                "updatedUntil",
                "page",
                "size",
                "sort",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_data_subject_profiles_unordered_v4(self, **kwargs) -> Response:
        """Get Optimized List of All Purpose Details for All Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/profiles/unordered",
            path_params=[],
            query_params=[
                "collectionPointId",
                "purposeId",
                "status",
                "updatedSince",
                "updatedUntil",
                "page",
                "size",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_data_subject_profile_v4(self, **kwargs) -> Response:
        """Get Purpose Details by Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/profiles/{purposeGuid}",
            path_params=["purposeGuid"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def search_data_subjects_by_element_v4(self, **kwargs) -> Response:
        """Search Data Subjects by Data Element"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/search-by-element",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_data_subjects_unordered_v4(self, **kwargs) -> Response:
        """Get Optimized List of Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/datasubjects/unordered",
            path_params=[],
            query_params=["fromDate", "toDate", "page", "size"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_data_subject_groups_list_v4(self, **kwargs) -> Response:
        """Get List of Data Subject Groups"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/groups",
            path_params=[],
            query_params=["page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def create_job_using_post(self, **kwargs) -> Response:
        """Create Job"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/jobs",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_linked_identity_groups_by_data_subject_v4(self, **kwargs) -> Response:
        """Get List of Data Subject Group Associations by Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/linkedidentitygroups",
            path_params=[],
            query_params=["linkedIdentityGroupId"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def create_data_subject_group_v4(self, **kwargs) -> Response:
        """Create Data Subject Group"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/linkedidentitygroups",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def update_data_subject_group_v4(self, **kwargs) -> Response:
        """Update Data Subject Group"""
        return self._call(
            http="PUT",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/linkedidentitygroups/{dataSubjectGroupId}",
            path_params=["dataSubjectGroupId"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def get_linked_identity_group_members_v4(self, **kwargs) -> Response:
        """Get List of Data Subject Group Members"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/linkedidentitygroups/{dataSubjectGroupId}/members",
            path_params=["dataSubjectGroupId"],
            query_params=["page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_email_link_tokens_list_v4(self, **kwargs) -> Response:
        """Get List of Data Subject Tokens"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/consent/v4/linktokens",
            path_params=[],
            query_params=["fromDate", "toDate", "page", "size", "sort"],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def upload_consent_attachments(self, **kwargs) -> Response:
        """Upload Consent Attachment"""
        return self._call(
            http="POST",
            url_template="https://__HOSTNAME__/rest/api/preferences/v1/attachments",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def download_given_consent_attachments(self, **kwargs) -> Response:
        """Download Consent Attachment"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/preferences/v1/attachments/{attachmentId}",
            path_params=["attachmentId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_given_consent_attachment_refs(self, **kwargs) -> Response:
        """Remove Consent Attachment"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/rest/api/preferences/v1/attachments-reference/{attachmentId}",
            path_params=["attachmentId"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def remove_all_consent_attachment_refs(self, **kwargs) -> Response:
        """Remove All Consent Attachments"""
        return self._call(
            http="DELETE",
            url_template="https://__HOSTNAME__/rest/api/preferences/v1/datasubjects/{identifier}/attachment-references",
            path_params=["identifier"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def download_consent_attachments(self, **kwargs) -> Response:
        """Download All Consent Attachments"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/preferences/v1/datasubjects/{identifier}/attachments",
            path_params=["identifier"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def get_v3_datasubject_profiles_using_post(self, **kwargs) -> Response:
        """Get List of Data Subjects"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/preferences/v3/datasubject-profiles",
            path_params=[],
            query_params=[
                "updatedSince",
                "updatedUntil",
                "collectionPointGuid",
                "purposeGuid",
                "page",
                "size",
                "sort",
            ],
            has_body=False,
            paginate="offset",
            kwargs=kwargs,
        )

    def get_v3_datasubjects_profile_using_get(self, **kwargs) -> Response:
        """Get Data Subject"""
        return self._call(
            http="GET",
            url_template="https://__HOSTNAME__/rest/api/preferences/v3/datasubjects/profile",
            path_params=[],
            query_params=["includeInstantLinkToken", "isDNCInclude"],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
