#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from onetrust_api.api.api_client_base import OneTrustApiBase
from onetrust_api.onetrust_models import Response


class OneTrustCookieConsentLegacy(OneTrustApiBase):
    def download_to_local_using_get(self, **kwargs) -> Response:
        """Download Script File"""
        return self._call(
            http='GET',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v1/script-integration/{domainId}/downloadscriptv2',
            path_params=['domainId'],
            query_params=[],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def request_bulk_add_domain_using_post(self, **kwargs) -> Response:
        """Add Websites to Scan"""
        return self._call(
            http='POST',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/websites',
            path_params=[],
            query_params=['externalOrgId'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_domains_scanned_by_sort_using_get(self, **kwargs) -> Response:
        """Get List of Websites"""
        return self._call(
            http='GET',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/websites',
            path_params=[],
            query_params=['externalOrgId', 'searchStr', 'page', 'size', 'sort'],
            has_body=False,
            paginate='offset',
            kwargs=kwargs,
        )

    def get_script_for_website_using_get(self, **kwargs) -> Response:
        """Get Script for Website"""
        return self._call(
            http='GET',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/websites/scripts',
            path_params=[],
            query_params=['website', 'scriptType'],
            has_body=False,
            paginate='none',
            kwargs=kwargs,
        )

    def publish_to_site_using_put(self, **kwargs) -> Response:
        """Publish Script to Website"""
        return self._call(
            http='PUT',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/websites/publish',
            path_params=[],
            query_params=['website', 'scriptType'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_new_cookie(self, **kwargs) -> Response:
        """Create Cookie"""
        return self._call(
            http='POST',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v1/cookies',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def update_cookie(self, **kwargs) -> Response:
        """Update Cookie"""
        return self._call(
            http='PUT',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v1/cookies',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_categorized_cookies_using_get(self, **kwargs) -> Response:
        """Categorize Cookies by Domain"""
        return self._call(
            http='POST',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/categorize',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_categorized_cookies_with_cookie_ids_using_get(self, **kwargs) -> Response:
        """Categorize Cookies by Domain and Cookie ID"""
        return self._call(
            http='POST',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/categorizewithids',
            path_params=[],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def create_domain_group_using_post(self, **kwargs) -> Response:
        """Create or Update Domain Group"""
        return self._call(
            http='POST',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v1/domains/{domainId}/domaingroup',
            path_params=['domainId'],
            query_params=[],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

    def get_cookie_reports_using_post(self, **kwargs) -> Response:
        """Get List of Cookies by Criteria"""
        return self._call(
            http='POST',
            url_template='https://customer.my.onetrust.com/api/cookiemanager/v2/cookie-reports/search',
            path_params=[],
            query_params=['language', 'countryCode', 'searchStr', 'page', 'size'],
            has_body=True,
            paginate='none',
            kwargs=kwargs,
        )

